package overlayruntime

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/sky1core/quota/internal/childprocess"
	"golang.org/x/sys/unix"
)

const sharedRule = "AGENTS.md"
const localRule = "AGENTS.local.md"
const sharedBridge = "CLAUDE.md"
const localBridge = "CLAUDE.local.md"
const localOwner = "<!-- generated by agents-local-overlay from the primary AGENTS.local.md; do not edit -->"
const sharedOwner = "<!-- generated by quota instructions from the primary AGENTS.md; do not edit -->"
const maxRuleBytes = 8 << 20

var errOutsideRepository = errors.New("run inside a Git worktree")

type repoContext struct {
	Start, Top, Root, Common string
	Worktrees                []string
	Context                  context.Context
	CodexHookRemovals        []string
	NativeCodexSettings      bool
	NativeCodexHookFiles     map[string][]string
	ValidatedCodexPlan       *CodexSetupPlan
}

func (r repoContext) Bare() bool { return r.Root == r.Common }
func (r repoContext) Checkouts() []string {
	var out []string
	for _, w := range r.Worktrees {
		if !r.Bare() || w != r.Root {
			out = append(out, w)
		}
	}
	return out
}
func (r repoContext) Copies() []string {
	var out []string
	for _, w := range r.Checkouts() {
		if w != r.Root {
			out = append(out, w)
		}
	}
	return out
}
func gitOutput(ctx context.Context, cwd string, args ...string) ([]byte, error) {
	return gitOutputInput(ctx, cwd, nil, args...)
}
func gitOutputInput(ctx context.Context, cwd string, input io.Reader, args ...string) ([]byte, error) {
	cmd := childprocess.CommandContext(ctx, "git", args...)
	cmd.Dir = cwd
	cmd.Stdin = input
	var out, stderr bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &stderr
	err := childprocess.Run(cmd)
	if err != nil {
		return out.Bytes(), fmt.Errorf("git %s failed: %s: %w", strings.Join(args, " "), strings.TrimSpace(stderr.String()), err)
	}
	return out.Bytes(), nil
}
func resolvePath(p string) string {
	a, e := filepath.Abs(p)
	if e == nil {
		p = a
	}
	v, e := filepath.EvalSymlinks(p)
	if e == nil {
		return v
	}
	parent := filepath.Dir(p)
	if parent != p {
		return filepath.Join(resolvePath(parent), filepath.Base(p))
	}
	return p
}
func onePath(data []byte) (string, error) {
	if !bytes.HasSuffix(data, []byte("\n")) || !utf8.Valid(data) {
		return "", fmt.Errorf("Git did not return a newline-terminated UTF-8 path")
	}
	return resolvePath(string(data[:len(data)-1])), nil
}
func resolveContext(ctx context.Context, dir string) (repoContext, error) {
	r := repoContext{Context: ctx}
	p, e := filepath.EvalSymlinks(dir)
	if e != nil {
		return r, fmt.Errorf("cannot enter project directory: %s: %w", dir, e)
	}
	r.Start = resolvePath(p)
	info, e := os.Stat(r.Start)
	if e != nil || !info.IsDir() {
		return r, fmt.Errorf("project directory is not a directory: %s", dir)
	}
	b, e := gitOutput(ctx, r.Start, "rev-parse", "--path-format=absolute", "--show-toplevel")
	if e != nil {
		return r, errOutsideRepository
	}
	r.Top, e = onePath(b)
	if e != nil {
		return r, e
	}
	b, e = gitOutput(ctx, r.Top, "rev-parse", "--path-format=absolute", "--git-common-dir")
	if e != nil {
		return r, e
	}
	r.Common, e = onePath(b)
	if e != nil {
		return r, e
	}
	b, e = gitOutput(ctx, r.Top, "worktree", "list", "--porcelain", "-z")
	if e != nil {
		return r, e
	}
	for _, v := range bytes.Split(b, []byte{0}) {
		if bytes.HasPrefix(v, []byte("worktree ")) {
			p := string(v[9:])
			if !utf8.ValidString(p) || !filepath.IsAbs(p) {
				return r, fmt.Errorf("worktree path is not absolute UTF-8")
			}
			r.Worktrees = append(r.Worktrees, resolvePath(p))
		}
	}
	if len(r.Worktrees) == 0 {
		return r, fmt.Errorf("could not resolve primary worktree")
	}
	r.Root = r.Worktrees[0]
	info, e = os.Stat(r.Root)
	if e != nil || !info.IsDir() {
		return r, fmt.Errorf("primary worktree path is not a directory")
	}
	return r, nil
}
func exists(p string) bool { _, e := os.Lstat(p); return e == nil || !os.IsNotExist(e) }
func within(p, root string) bool {
	rel, e := filepath.Rel(resolvePath(root), resolvePath(p))
	return e == nil && rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator))
}
func readRegular(path string) ([]byte, error) {
	info, e := os.Lstat(path)
	if e != nil {
		return nil, e
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return nil, fmt.Errorf("%s is a symlink; not a regular file", path)
	}
	if !info.Mode().IsRegular() {
		return nil, fmt.Errorf("%s is not a regular file", path)
	}
	var before unix.Stat_t
	if e = unix.Lstat(path, &before); e != nil {
		return nil, e
	}
	if before.Uid != uint32(os.Getuid()) {
		return nil, fmt.Errorf("%s is not owned by current user", path)
	}
	fd, e := unix.Open(path, unix.O_RDONLY|unix.O_NONBLOCK|unix.O_NOFOLLOW|unix.O_CLOEXEC, 0)
	if e != nil {
		return nil, fmt.Errorf("could not read %s: %w", path, e)
	}
	f := os.NewFile(uintptr(fd), path)
	defer f.Close()
	opened, e := f.Stat()
	if e != nil {
		return nil, e
	}
	if !opened.Mode().IsRegular() || !os.SameFile(info, opened) {
		return nil, fmt.Errorf("%s changed during inspection", path)
	}
	if opened.Size() > maxRuleBytes {
		return nil, fmt.Errorf("%s exceeds %d-byte file size limit", path, maxRuleBytes)
	}
	data, e := io.ReadAll(io.LimitReader(f, maxRuleBytes+1))
	if e != nil {
		return nil, e
	}
	if len(data) > maxRuleBytes {
		return nil, fmt.Errorf("%s exceeds file size limit", path)
	}
	after, e := os.Lstat(path)
	if e != nil {
		return nil, e
	}
	if !os.SameFile(opened, after) || opened.Size() != after.Size() || !opened.ModTime().Equal(after.ModTime()) {
		return nil, fmt.Errorf("%s changed during inspection", path)
	}
	var afterStat, openedAfter unix.Stat_t
	if e = unix.Lstat(path, &afterStat); e != nil {
		return nil, e
	}
	if e = unix.Fstat(fd, &openedAfter); e != nil {
		return nil, e
	}
	if !sameFileSnapshot(before, afterStat) || !sameFileSnapshot(before, openedAfter) {
		return nil, fmt.Errorf("%s changed during inspection", path)
	}
	return data, nil
}
func sameFileSnapshot(a, b unix.Stat_t) bool {
	return a.Dev == b.Dev && a.Ino == b.Ino && a.Mode == b.Mode && a.Uid == b.Uid && a.Size == b.Size && a.Mtim == b.Mtim && a.Ctim == b.Ctim
}
func decodeRule(data []byte, path string) (string, error) {
	if !utf8.Valid(data) {
		return "", fmt.Errorf("rule file is not UTF-8: %s", path)
	}
	if bytes.IndexByte(data, 0) >= 0 {
		return "", fmt.Errorf("rule file contains NUL: %s", path)
	}
	return strings.TrimRight(string(data), "\n"), nil
}
func readRule(path string) (string, error) {
	b, e := readRegular(path)
	if e != nil {
		return "", e
	}
	return decodeRule(b, path)
}
func atomicWrite(path string, data []byte, private bool, expected ...[]byte) error {
	return atomicWriteFile(path, data, private, false, expected...)
}

func atomicWriteFile(path string, data []byte, private, ownerExecutable bool, expected ...[]byte) error {
	mode := os.FileMode(0o644)
	before, e := os.Lstat(path)
	if e == nil {
		if !before.Mode().IsRegular() {
			return fmt.Errorf("%s is not a regular file", path)
		}
		var ownership unix.Stat_t
		if e = unix.Lstat(path, &ownership); e != nil {
			return e
		}
		if ownership.Uid != uint32(os.Getuid()) {
			return fmt.Errorf("%s is not owned by current user", path)
		}
		mode = before.Mode().Perm()
	} else if !os.IsNotExist(e) {
		return e
	}
	if len(expected) > 0 {
		if before == nil {
			if expected[0] != nil {
				return fmt.Errorf("%s changed before write", path)
			}
		} else {
			if expected[0] == nil {
				return fmt.Errorf("%s appeared before write", path)
			}
			current, e := readRegular(path)
			if e != nil {
				return e
			}
			if !bytes.Equal(current, expected[0]) {
				return fmt.Errorf("%s changed before write", path)
			}
		}
	}
	if private {
		allowed := os.FileMode(0o600)
		if ownerExecutable {
			allowed |= 0o100
			mode |= 0o100
		}
		mode &= allowed
	}
	f, e := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+"-*")
	if e != nil {
		return e
	}
	tmp := f.Name()
	defer os.Remove(tmp)
	if _, e = f.Write(data); e == nil {
		e = f.Sync()
	}
	if ce := f.Close(); e == nil {
		e = ce
	}
	if e != nil {
		return e
	}
	if before == nil {
		probe, e := os.OpenFile(tmp+".mode", os.O_CREATE|os.O_EXCL|os.O_WRONLY, mode)
		if e != nil {
			return e
		}
		pi, e := probe.Stat()
		probe.Close()
		os.Remove(tmp + ".mode")
		if e != nil {
			return e
		}
		mode = pi.Mode().Perm()
	}
	if e = os.Chmod(tmp, mode); e != nil {
		return e
	}
	after, e := os.Lstat(path)
	if before == nil {
		if !os.IsNotExist(e) {
			return fmt.Errorf("%s changed during write", path)
		}
	} else if e != nil || !os.SameFile(before, after) || before.Mode() != after.Mode() || before.Size() != after.Size() || !before.ModTime().Equal(after.ModTime()) {
		return fmt.Errorf("%s changed during write", path)
	}
	return os.Rename(tmp, path)
}
func (r repoContext) tracked(w, rel string) (bool, error) {
	_, e := gitOutput(r.Context, w, "ls-files", "--error-unmatch", "--", ":(icase,literal)"+rel)
	return gitBoolean(e)
}
func (r repoContext) ignored(w, rel string) (bool, error) {
	_, e := gitOutput(r.Context, w, "check-ignore", "-q", "--", rel)
	return gitBoolean(e)
}
func gitBoolean(e error) (bool, error) {
	if e == nil {
		return true, nil
	}
	var exit interface{ ExitCode() int }
	if errors.As(e, &exit) && exit.ExitCode() == 1 {
		return false, nil
	}
	return false, e
}
func (r repoContext) localSource() string { return filepath.Join(r.Root, localRule) }
func (r repoContext) ensureLocalSource() error {
	if r.Bare() {
		return nil
	}
	tracked, e := r.tracked(r.Root, localRule)
	if e != nil {
		return e
	}
	if tracked {
		return fmt.Errorf("%s is tracked; it must stay local-only", r.localSource())
	}
	return nil
}
func (r repoContext) ensureLocalTarget(w string) error {
	tracked, e := r.tracked(w, localBridge)
	if e != nil {
		return e
	}
	if tracked {
		return fmt.Errorf("%s is tracked; it must stay local-only", filepath.Join(w, localBridge))
	}
	ignored, e := r.ignored(w, localBridge)
	if e != nil {
		return e
	}
	if !ignored {
		return fmt.Errorf("%s is not git-ignored; run: %s setup", filepath.Join(w, localBridge), cliName)
	}
	return nil
}

type RepositoryState struct {
	snapshot       *[]byte
	Disabled       map[string]bool   `json:"disabled"`
	SharedSource   string            `json:"shared_source"`
	Generated      map[string]string `json:"generated,omitempty"`
	GeneratedModes map[string]uint32 `json:"generated_modes,omitempty"`
	LocalFiles     []string          `json:"local_files,omitempty"`
	NativeCodex    bool              `json:"native_codex,omitempty"`
}

func statePath(r repoContext) string { return filepath.Join(r.Common, "quota-instructions.json") }

func recordGeneratedFile(state *RepositoryState, path string, data []byte) error {
	info, err := os.Lstat(path)
	if err != nil {
		return err
	}
	if !info.Mode().IsRegular() {
		return fmt.Errorf("%s is not a regular generated file", path)
	}
	if state.Generated == nil {
		state.Generated = map[string]string{}
	}
	if state.GeneratedModes == nil {
		state.GeneratedModes = map[string]uint32{}
	}
	state.Generated[path] = digest(data)
	state.GeneratedModes[path] = uint32(info.Mode())
	return nil
}

func checkRecordedGeneratedMode(path string, state RepositoryState) error {
	mode, recorded := state.GeneratedModes[path]
	if !recorded {
		return nil
	}
	info, err := os.Lstat(path)
	if err != nil {
		return err
	}
	if !info.Mode().IsRegular() {
		return fmt.Errorf("%s is not a regular file; file preserved", path)
	}
	if info.Mode() != os.FileMode(mode) {
		return fmt.Errorf("%s permissions changed after generation; file preserved", path)
	}
	return nil
}
func readState(r repoContext) (RepositoryState, error) {
	s := RepositoryState{Disabled: map[string]bool{}, SharedSource: "checkout", Generated: map[string]string{}, snapshot: new([]byte)}
	p := statePath(r)
	if !exists(p) {
		return s, nil
	}
	info, e := os.Lstat(p)
	if e != nil {
		return s, e
	}
	if info.Mode().Perm()&0o077 != 0 {
		return s, fmt.Errorf("%s requires owner-only permissions", p)
	}
	var st unix.Stat_t
	if e = unix.Lstat(p, &st); e != nil {
		return s, e
	}
	if st.Uid != uint32(os.Getuid()) {
		return s, fmt.Errorf("%s is not owned by current user", p)
	}
	b, e := readRegular(p)
	if e != nil {
		return s, e
	}
	dec := json.NewDecoder(bytes.NewReader(b))
	dec.DisallowUnknownFields()
	var parsed RepositoryState
	if e = dec.Decode(&parsed); e != nil {
		return s, fmt.Errorf("parse repository instructions state: %w", e)
	}
	if parsed.SharedSource != "checkout" && parsed.SharedSource != "primary" {
		return s, fmt.Errorf("invalid shared_source in repository instructions state")
	}
	if parsed.Disabled == nil {
		return s, fmt.Errorf("repository instructions state missing disabled object")
	}
	for agent := range parsed.Disabled {
		if agent != "claude" && agent != "codex" {
			return s, fmt.Errorf("unknown disabled agent %q", agent)
		}
	}
	if e = dec.Decode(new(any)); e != io.EOF {
		return s, fmt.Errorf("invalid trailing repository instructions state")
	}
	if parsed.Generated == nil {
		parsed.Generated = map[string]string{}
	}
	if e = validateLocalFiles(parsed.LocalFiles); e != nil {
		return s, fmt.Errorf("invalid local_files in repository instructions state: %w", e)
	}
	parsed.snapshot = new([]byte)
	*parsed.snapshot = b
	return parsed, nil
}
func ReadRepositoryState(ctx context.Context, dir string) (RepositoryState, error) {
	if e := ValidateGitEnvironment(ctx); e != nil {
		return RepositoryState{}, e
	}
	r, e := resolveContext(ctx, dir)
	if e != nil {
		return RepositoryState{}, e
	}
	return readState(r)
}
func withRepositoryLock(r repoContext, fn func() error) error {
	p := filepath.Join(r.Common, "quota-instructions.lock")
	fd, e := unix.Open(p, unix.O_RDWR|unix.O_CREAT|unix.O_NOFOLLOW|unix.O_NONBLOCK|unix.O_CLOEXEC, 0o600)
	if e != nil {
		return e
	}
	defer unix.Close(fd)
	var st unix.Stat_t
	if e = unix.Fstat(fd, &st); e != nil {
		return e
	}
	if st.Mode&unix.S_IFMT != unix.S_IFREG || st.Uid != uint32(os.Getuid()) || st.Mode&0o077 != 0 {
		return fmt.Errorf("unsafe repository instructions lock")
	}
	for {
		e = unix.Flock(fd, unix.LOCK_EX|unix.LOCK_NB)
		if e == nil {
			break
		}
		if e != unix.EAGAIN && e != unix.EWOULDBLOCK {
			return e
		}
		select {
		case <-r.Context.Done():
			return r.Context.Err()
		case <-time.After(10 * time.Millisecond):
		}
	}
	defer unix.Flock(fd, unix.LOCK_UN)
	return fn()
}
func writeState(r repoContext, s RepositoryState) error {
	b, e := json.MarshalIndent(s, "", "  ")
	if e != nil {
		return e
	}
	data := append(b, '\n')
	if old, e := readRegular(statePath(r)); e == nil && bytes.Equal(old, data) {
		return nil
	}
	if s.snapshot == nil {
		return fmt.Errorf("repository state lacks an inspected snapshot")
	}
	if e = atomicWrite(statePath(r), data, true, *s.snapshot); e != nil {
		return e
	}
	*s.snapshot = append([]byte{}, data...)
	return nil
}
func UpdateRepositoryState(ctx context.Context, dir string, update func(*RepositoryState) error) error {
	if e := ValidateGitEnvironment(ctx); e != nil {
		return e
	}
	r, e := resolveContext(ctx, dir)
	if e != nil {
		return e
	}
	return withRepositoryLock(r, func() error {
		s, e := readState(r)
		if e != nil {
			return e
		}
		if e = update(&s); e != nil {
			return e
		}
		if s.SharedSource != "checkout" && s.SharedSource != "primary" {
			return fmt.Errorf("invalid shared source policy")
		}
		if e = validateLocalFiles(s.LocalFiles); e != nil {
			return e
		}
		return writeState(r, s)
	})
}
