package overlayruntime

import (
	"bytes"
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func isolateAgentConfig(t *testing.T) {
	t.Helper()
	t.Setenv("CLAUDE_CONFIG_DIR", t.TempDir())
	t.Setenv("CODEX_HOME", t.TempDir())
}

func git(t *testing.T, dir string, args ...string) string {
	t.Helper()
	if err := ValidateGitEnvironment(context.Background()); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %s failed: %v\n%s", strings.Join(args, " "), err, out)
	}
	return strings.TrimSpace(string(out))
}

func newRepo(t *testing.T) string {
	t.Helper()
	isolateAgentConfig(t)
	dir := t.TempDir()
	resolved, err := filepath.EvalSymlinks(dir)
	if err != nil {
		t.Fatalf("evalsymlinks: %v", err)
	}
	git(t, resolved, "init", "-q")
	return resolved
}

func seedCommit(t *testing.T, repo string) {
	t.Helper()
	for key, value := range map[string]string{"user.name": "Overlay Test", "user.email": "overlay-test@example.invalid"} {
		cmd := exec.Command("git", "config", "--get", key)
		cmd.Dir = repo
		if err := cmd.Run(); err != nil {
			var status *exec.ExitError
			if !errors.As(err, &status) || status.ExitCode() != 1 {
				t.Fatalf("git config %s: %v", key, err)
			}
			git(t, repo, "config", "--local", key, value)
		}
	}
	git(t, repo, "commit", "-q", "-m", "seed")
}

func write(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func run(t *testing.T, stdin string, args ...string) (int, string, string) {
	t.Helper()
	var out, errb bytes.Buffer
	code := Run(context.Background(), args, strings.NewReader(stdin), &out, &errb)
	return code, out.String(), errb.String()
}

func quote(s string) string {
	return `"` + strings.ReplaceAll(s, `\`, `\\`) + `"`
}

func TestRunRejectsMalformedForms(t *testing.T) {
	cases := [][]string{
		{},
		{"json", "SessionStart", "a", "b", "c"}, // too few operands
		{"json", "SessionStart", "a", "b", "c", "d", "extra"}, // too many
		{"setup", "dir", "extra"},                             // too many
		{"check", "dir", "extra"},                             // too many
		{"claude-worktree-create", "unexpected"},              // takes none
		{"claude-worktree-remove", "unexpected"},              // takes none
		{"bogus"},                                             // unknown
	}
	for _, args := range cases {
		code, out, errb := run(t, "", args...)
		if code != 2 {
			t.Errorf("args %v: exit=%d, want 2 (out=%q err=%q)", args, code, out, errb)
		}
		if out != "" {
			t.Errorf("args %v: stdout should stay empty on rejection, got %q", args, out)
		}
		if !strings.Contains(errb, cliName) {
			t.Errorf("args %v: stderr %q missing %q", args, errb, cliName)
		}
	}
}

func TestCheckDeterministic(t *testing.T) {
	repo := newRepo(t)
	write(t, filepath.Join(repo, "AGENTS.md"), "# shared rules\n")

	code, out, errb := run(t, "", "check", repo)
	if code != 1 {
		t.Fatalf("check before setup: exit=%d, want 1 (out=%q err=%q)", code, out, errb)
	}
	if !strings.Contains(out, "FAIL") {
		t.Fatalf("check before setup: expected FAIL line, got %q / %q", out, errb)
	}

	code, out, errb = run(t, "", "setup", repo)
	if code != 0 {
		t.Fatalf("setup: exit=%d, want 0 (out=%q err=%q)", code, out, errb)
	}

	bridge, err := os.ReadFile(filepath.Join(repo, "CLAUDE.md"))
	if err != nil {
		t.Fatalf("read CLAUDE.md: %v", err)
	}
	if strings.TrimSpace(string(bridge)) != "@AGENTS.md" {
		t.Fatalf("bridge = %q, want @AGENTS.md", bridge)
	}

	code, out, errb = run(t, "", "check", repo)
	if code != 0 {
		t.Fatalf("check after setup: exit=%d, want 0 (out=%q err=%q)", code, out, errb)
	}
}

func TestLocalOwnerMarkerPreserved(t *testing.T) {
	repo := newRepo(t)
	write(t, filepath.Join(repo, "AGENTS.md"), "# shared\n")
	write(t, filepath.Join(repo, "AGENTS.local.md"), "# local secret rules\n")
	write(t, filepath.Join(repo, "CLAUDE.md"), "@AGENTS.md\n")
	git(t, repo, "add", "AGENTS.md", "CLAUDE.md")
	seedCommit(t, repo)

	linked := repo + "-wt"
	t.Cleanup(func() { os.RemoveAll(linked) })
	git(t, repo, "worktree", "add", "-q", linked, "HEAD")

	code, out, errb := run(t, "", "setup", repo)
	if code != 0 {
		t.Fatalf("setup: exit=%d (out=%q err=%q)", code, out, errb)
	}
	if strings.Contains(out+errb, "agents-overlay-context") {
		t.Fatalf("output leaked old helper name: out=%q err=%q", out, errb)
	}

	copyPath := filepath.Join(linked, "CLAUDE.local.md")
	data, err := os.ReadFile(copyPath)
	if err != nil {
		t.Fatalf("read generated copy: %v", err)
	}
	const wantOwner = "<!-- generated by agents-local-overlay from the primary AGENTS.local.md; do not edit -->"
	if !strings.HasPrefix(string(data), wantOwner) {
		t.Fatalf("generated copy owner marker changed: %q", data)
	}
	if !strings.Contains(string(data), "local secret rules") {
		t.Fatalf("generated copy missing rule body: %q", data)
	}
}

func TestJSONSessionEmitsNotice(t *testing.T) {
	repo := newRepo(t)
	write(t, filepath.Join(repo, "AGENTS.md"), "# shared\n")
	write(t, filepath.Join(repo, "AGENTS.local.md"), "# local\n")
	hookJSON := `{"cwd":` + quote(repo) + `}`
	code, out, errb := run(t, hookJSON, "json", "SessionStart", "x", "y", repo, "claude-session")
	if code != 0 {
		t.Fatalf("json hook: exit=%d, want 0 (err=%q)", code, errb)
	}
	if !strings.Contains(out, "[agents-local-overlay] ") {
		t.Fatalf("expected notice channel prefix, got stdout=%q stderr=%q", out, errb)
	}
}

func TestClaudeWorktreeCreateRemove(t *testing.T) {
	repo := newRepo(t)
	write(t, filepath.Join(repo, "AGENTS.md"), "# shared\n")
	git(t, repo, "add", "AGENTS.md")
	seedCommit(t, repo)

	base := t.TempDir()
	t.Setenv("AGENTS_OVERLAY_CLAUDE_WORKTREE_DIR", base)

	createJSON := `{"cwd":` + quote(repo) + `,"name":"feature1"}`
	code, out, errb := run(t, createJSON, "claude-worktree-create")
	if code != 0 {
		t.Fatalf("worktree-create: exit=%d (out=%q err=%q)", code, out, errb)
	}
	created := strings.TrimSpace(out)
	if created == "" {
		t.Fatalf("worktree-create printed no path (err=%q)", errb)
	}
	if _, err := os.Stat(created); err != nil {
		t.Fatalf("created worktree missing: %v", err)
	}

	removeJSON := `{"cwd":` + quote(repo) + `,"worktree_path":` + quote(created) + `}`
	code, out, errb = run(t, removeJSON, "claude-worktree-remove")
	if code != 0 {
		t.Fatalf("worktree-remove: exit=%d (out=%q err=%q)", code, out, errb)
	}
	if _, err := os.Stat(created); !os.IsNotExist(err) {
		t.Fatalf("worktree still present after remove: err=%v", err)
	}
}

func TestDirtyWorktreePreserved(t *testing.T) {
	repo := newRepo(t)
	write(t, filepath.Join(repo, "AGENTS.md"), "# shared\n")
	write(t, filepath.Join(repo, "AGENTS.local.md"), "# local\n")
	git(t, repo, "add", "AGENTS.md")
	seedCommit(t, repo)

	base := t.TempDir()
	t.Setenv("AGENTS_OVERLAY_CLAUDE_WORKTREE_DIR", base)

	createJSON := `{"cwd":` + quote(repo) + `,"name":"feature"}`
	code, out, errb := run(t, createJSON, "claude-worktree-create")
	if code != 0 {
		t.Fatalf("worktree-create: exit=%d (out=%q err=%q)", code, out, errb)
	}
	created := strings.TrimSpace(out)

	dirty := filepath.Join(created, "keepme.txt")
	write(t, dirty, "work in progress\n")

	removeJSON := `{"cwd":` + quote(repo) + `,"worktree_path":` + quote(created) + `}`
	code, out, errb = run(t, removeJSON, "claude-worktree-remove")
	if code == 0 {
		t.Fatalf("worktree-remove should refuse a dirty worktree (out=%q err=%q)", out, errb)
	}
	if _, err := os.Stat(created); err != nil {
		t.Fatalf("dirty worktree removed despite untracked work: %v", err)
	}
	data, err := os.ReadFile(dirty)
	if err != nil {
		t.Fatalf("dirty file not preserved: %v", err)
	}
	if string(data) != "work in progress\n" {
		t.Fatalf("dirty file changed: %q", data)
	}
}

func TestBareRepoLinkedLocalCopy(t *testing.T) {
	origin := newRepo(t)
	write(t, filepath.Join(origin, "AGENTS.md"), "# shared\n")
	write(t, filepath.Join(origin, "CLAUDE.md"), "@AGENTS.md\n")
	git(t, origin, "add", "AGENTS.md", "CLAUDE.md")
	seedCommit(t, origin)

	bare := origin + "-bare.git"
	t.Cleanup(func() { os.RemoveAll(bare) })
	git(t, origin, "clone", "--bare", "-q", origin, bare)

	write(t, filepath.Join(bare, "AGENTS.local.md"), "# bare local rules\n")

	linked := origin + "-wt"
	t.Cleanup(func() { os.RemoveAll(linked) })
	git(t, bare, "worktree", "add", "-q", linked, "HEAD")

	code, out, errb := run(t, "", "setup", linked)
	if code != 0 {
		t.Fatalf("setup: exit=%d (out=%q err=%q)", code, out, errb)
	}

	copyPath := filepath.Join(linked, "CLAUDE.local.md")
	data, err := os.ReadFile(copyPath)
	if err != nil {
		t.Fatalf("read generated copy: %v", err)
	}
	const wantOwner = "<!-- generated by agents-local-overlay from the primary AGENTS.local.md; do not edit -->"
	if !strings.HasPrefix(string(data), wantOwner) {
		t.Fatalf("generated copy owner marker changed: %q", data)
	}
	if !strings.Contains(string(data), "bare local rules") {
		t.Fatalf("generated copy missing rule body: %q", data)
	}

	code, out, errb = run(t, "", "check", linked)
	if code != 0 {
		t.Fatalf("check after setup: exit=%d (out=%q err=%q)", code, out, errb)
	}
}

func TestSymlinkLocalSourceRefused(t *testing.T) {
	repo := newRepo(t)
	write(t, filepath.Join(repo, "AGENTS.md"), "# shared\n")
	target := filepath.Join(repo, "real-local.md")
	write(t, target, "# sneaky content\n")
	if err := os.Symlink(target, filepath.Join(repo, "AGENTS.local.md")); err != nil {
		t.Fatalf("symlink: %v", err)
	}

	code, out, errb := run(t, "", "setup", repo)
	if code != 1 {
		t.Fatalf("setup: exit=%d, want 1 (out=%q err=%q)", code, out, errb)
	}
	if !strings.Contains(out+errb, "symlink") {
		t.Fatalf("expected symlink refusal, got out=%q err=%q", out, errb)
	}
}

func TestUnownedLocalCopyRefused(t *testing.T) {
	repo := newRepo(t)
	write(t, filepath.Join(repo, "AGENTS.md"), "# shared\n")
	write(t, filepath.Join(repo, "AGENTS.local.md"), "# local\n")
	write(t, filepath.Join(repo, "CLAUDE.md"), "@AGENTS.md\n")
	git(t, repo, "add", "AGENTS.md", "CLAUDE.md")
	seedCommit(t, repo)

	linked := repo + "-wt"
	t.Cleanup(func() { os.RemoveAll(linked) })
	git(t, repo, "worktree", "add", "-q", linked, "HEAD")

	foreign := "# hand-written, not overlay-owned\n"
	copyPath := filepath.Join(linked, "CLAUDE.local.md")
	write(t, copyPath, foreign)

	code, out, errb := run(t, "", "setup", repo)
	if code != 1 {
		t.Fatalf("setup: exit=%d, want 1 (out=%q err=%q)", code, out, errb)
	}
	if !strings.Contains(out+errb, "not overlay-generated") {
		t.Fatalf("expected unowned-copy refusal, got out=%q err=%q", out, errb)
	}
	data, err := os.ReadFile(copyPath)
	if err != nil {
		t.Fatalf("read foreign copy: %v", err)
	}
	if string(data) != foreign {
		t.Fatalf("foreign copy was modified: %q", data)
	}
}

func TestNativeRuntimeWithoutPython(t *testing.T) {
	repo := newRepo(t)
	write(t, filepath.Join(repo, "AGENTS.md"), "# shared\n")
	gitBin, err := exec.LookPath("git")
	if err != nil {
		t.Fatal(err)
	}
	path := t.TempDir()
	if err = os.Symlink(gitBin, filepath.Join(path, "git")); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", path)
	if code, out, errb := run(t, "", "setup", "--runtime=codex", repo); code != 0 {
		t.Fatalf("native setup without Python: %d %s %s", code, out, errb)
	}
}
