package main

import (
	"bytes"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func callInstructionsWorktreeHook(t *testing.T, event string, payload map[string]string, want int) string {
	t.Helper()
	input, err := json.Marshal(payload)
	if err != nil {
		t.Fatal(err)
	}
	var stdout, stderr bytes.Buffer
	code := runAgentInstructions([]string{"_hook", "--agent=claude", "--event=" + event}, bytes.NewReader(input), &stdout, &stderr)
	if code != want {
		t.Fatalf("%s: exit=%d want=%d stdout=%s stderr=%s", event, code, want, &stdout, &stderr)
	}
	if want != 0 {
		if stdout.Len() != 0 {
			t.Fatalf("failed hook returned a path: %s", &stdout)
		}
		return stderr.String()
	}
	return strings.TrimSpace(stdout.String())
}

func nativeWorktreeExistingSnapshot(t *testing.T, f nativeSetupFixture, includeState bool) map[string]string {
	t.Helper()
	snapshot := f.snapshot(t)
	for path := range snapshot {
		if strings.HasPrefix(path, filepath.Join(f.repo, ".git")+string(filepath.Separator)) {
			if includeState && (path == filepath.Join(f.repo, ".git", "quota-instructions.json") || path == filepath.Join(f.repo, ".git", "info", "exclude")) {
				continue
			}
			delete(snapshot, path)
		}
	}
	return snapshot
}

func setupNativeWorktree(t *testing.T, f nativeSetupFixture, agent string, options ...string) {
	t.Helper()
	if f.linked != "" {
		if err := os.Rename(filepath.Join(f.linked, "AGENTS.md"), filepath.Join(f.linked, "original-shared.md")); err != nil {
			t.Fatal(err)
		}
	}
	var stdout, stderr bytes.Buffer
	args := append([]string{"setup", f.repo, "--agent=" + agent, "--shared-source=primary"}, options...)
	if code := runAgentInstructions(args, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("setup: exit=%d stdout=%s stderr=%s", code, &stdout, &stderr)
	}
	t.Setenv("AGENTS_OVERLAY_CLAUDE_WORKTREE_DIR", filepath.Join(f.home, "worktrees"))
}

func TestInstructionsNativeWorktreeUsesEffectiveBudget(t *testing.T) {
	f := newNativeSetupFixture(t, true)
	f.wrapper(t, "project_doc_max_bytes=65536", "")
	writeNativeSetupFile(t, filepath.Join(f.repo, "AGENTS.local.md"), strings.Repeat("한", 14000))
	setupNativeWorktree(t, f, "all")
	shared, local := "updated shared\n", strings.Repeat("글", 14000)+"\nprivate end\n"
	writeNativeSetupFile(t, filepath.Join(f.repo, "AGENTS.md"), shared)
	writeNativeSetupFile(t, filepath.Join(f.repo, "AGENTS.local.md"), local)
	before := nativeWorktreeExistingSnapshot(t, f, false)
	target := callInstructionsWorktreeHook(t, "WorktreeCreate", map[string]string{"cwd": f.repo, "name": "native-budget"}, 0)
	for rel, want := range map[string]string{
		"AGENTS.md":          shared,
		"AGENTS.local.md":    local,
		"AGENTS.override.md": shared + "\n" + local,
		"CLAUDE.md":          "@AGENTS.md\n",
		"CLAUDE.local.md":    "<!-- generated by agents-local-overlay from the primary AGENTS.local.md; do not edit -->\n\n" + local,
	} {
		body, err := os.ReadFile(filepath.Join(target, rel))
		if err != nil || string(body) != want {
			t.Fatalf("incomplete %s: bytes=%d want=%d err=%v", rel, len(body), len(want), err)
		}
	}
	if !reflect.DeepEqual(before, nativeWorktreeExistingSnapshot(t, f, false)) {
		t.Fatal("worktree creation refreshed existing checkout or account files")
	}
	callInstructionsWorktreeHook(t, "WorktreeRemove", map[string]string{"worktree_path": target}, 0)
	if _, err := os.Stat(target); !os.IsNotExist(err) {
		t.Fatalf("worktree was not removed: %v", err)
	}
}

func TestInstructionsNativeWorktreeRejectsAndRollsBack(t *testing.T) {
	for _, tc := range []struct{ name, setting, issue string }{
		{"budget", "project_doc_max_bytes=1", "over effective Codex"},
		{"discovery", "project_root_markers=[]", "project_root_markers"},
		{"fallback", `project_doc_fallback_filenames=["EXAMPLE.md"]`, "project_doc_fallback_filenames"},
		{"untrusted", "", "explicitly untrusted in effective Codex config"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			f := newNativeSetupFixture(t, true)
			setupNativeWorktree(t, f, "all")
			setting := tc.setting
			if tc.name == "untrusted" {
				setting = "projects." + f.repo + ".trust_level='untrusted'"
			}
			f.wrapper(t, setting, "")
			writeNativeSetupFile(t, filepath.Join(f.repo, "AGENTS.local.md"), "changed source\n")
			before := nativeWorktreeExistingSnapshot(t, f, true)
			worktrees := nativeWorktreeGit(t, f.repo, "worktree", "list", "--porcelain")
			branches := nativeWorktreeGit(t, f.repo, "for-each-ref", "--format=%(refname):%(objectname)", "refs/heads")
			failure := callInstructionsWorktreeHook(t, "WorktreeCreate", map[string]string{"cwd": f.repo, "name": "incompatible"}, 1)
			if !strings.Contains(failure, tc.issue) || strings.Contains(failure, "rollback incomplete") {
				t.Fatalf("unexpected worktree refusal: %s", failure)
			}
			if !reflect.DeepEqual(before, nativeWorktreeExistingSnapshot(t, f, true)) {
				t.Fatal("native rejection changed existing source, managed files, state or account files")
			}
			if worktrees != nativeWorktreeGit(t, f.repo, "worktree", "list", "--porcelain") || branches != nativeWorktreeGit(t, f.repo, "for-each-ref", "--format=%(refname):%(objectname)", "refs/heads") {
				t.Fatal("native rejection left a registered worktree or branch")
			}
			matches, err := filepath.Glob(filepath.Join(f.home, "worktrees", "*", "incompatible"))
			if err != nil || len(matches) != 0 {
				t.Fatalf("native rejection left target files: %v %v", matches, err)
			}
		})
	}
}

func TestInstructionsNativeWorktreeWithoutLocalSourcePreservesExistingFiles(t *testing.T) {
	f := newNativeSetupFixture(t, true)
	setupNativeWorktree(t, f, "all")
	if err := os.Rename(filepath.Join(f.repo, "AGENTS.local.md"), filepath.Join(f.repo, "saved-private.md")); err != nil {
		t.Fatal(err)
	}
	before := nativeWorktreeExistingSnapshot(t, f, false)
	target := callInstructionsWorktreeHook(t, "WorktreeCreate", map[string]string{"cwd": f.repo, "name": "shared-only"}, 0)
	for _, rel := range []string{"AGENTS.local.md", "AGENTS.override.md", "CLAUDE.local.md"} {
		if _, err := os.Stat(filepath.Join(target, rel)); !os.IsNotExist(err) {
			t.Fatalf("missing local source produced %s: %v", rel, err)
		}
	}
	if !reflect.DeepEqual(before, nativeWorktreeExistingSnapshot(t, f, false)) {
		t.Fatal("worktree preparation changed existing files after local source removal")
	}
	callInstructionsWorktreeHook(t, "WorktreeRemove", map[string]string{"worktree_path": target}, 0)
}

func TestInstructionsNativeWorktreeChecksActivePlannedHooks(t *testing.T) {
	for _, active := range []bool{true, false} {
		t.Run(map[bool]string{true: "active", false: "disabled"}[active], func(t *testing.T) {
			f := newNativeSetupFixture(t, true)
			hooks, err := os.ReadFile(filepath.Join(f.account, "hooks.json"))
			if err != nil {
				t.Fatal(err)
			}
			const rel = "config/hooks.json"
			writeNativeSetupFile(t, filepath.Join(f.repo, rel), "{}")
			writeNativeSetupFile(t, filepath.Join(f.repo, ".git", "info", "exclude"), "/AGENTS.local.md\n/"+rel+"\n")
			if err := os.Mkdir(filepath.Join(f.repo, ".codex"), 0700); err != nil {
				t.Fatal(err)
			}
			if err := os.Symlink("../"+rel, filepath.Join(f.repo, ".codex", "hooks.json")); err != nil {
				t.Fatal(err)
			}
			nativeWorktreeGit(t, f.repo, "add", ".codex/hooks.json")
			nativeWorktreeGit(t, f.repo, "-c", "user.name=Example", "-c", "user.email=example@example.invalid", "commit", "-qm", "fixture hooks alias")
			setupNativeWorktree(t, f, "all", "--local-file="+rel)
			writeNativeSetupFile(t, filepath.Join(f.repo, rel), string(hooks))
			if active {
				wrapper := "#!/bin/sh\nexec " + nativeSetupQuote(f.codex) + " -c \"projects.$PWD.trust_level='trusted'\" \"$@\"\n"
				writeNativeSetupFile(t, filepath.Join(f.bin, "codex"), wrapper)
			} else {
				writeNativeSetupFile(t, filepath.Join(f.account, "config.toml"), "")
			}
			before := nativeWorktreeExistingSnapshot(t, f, true)
			worktrees := nativeWorktreeGit(t, f.repo, "worktree", "list", "--porcelain")
			branches := nativeWorktreeGit(t, f.repo, "for-each-ref", "--format=%(refname):%(objectname)", "refs/heads")
			want := 0
			if active {
				want = 1
			}
			result := callInstructionsWorktreeHook(t, "WorktreeCreate", map[string]string{"cwd": f.repo, "name": "planned-hooks"}, want)
			if active {
				if !strings.Contains(result, "conflicts with native instruction delivery") || strings.Contains(result, "rollback incomplete") {
					t.Fatalf("active planned hook not rejected: %s", result)
				}
				if !reflect.DeepEqual(before, nativeWorktreeExistingSnapshot(t, f, true)) || worktrees != nativeWorktreeGit(t, f.repo, "worktree", "list", "--porcelain") || branches != nativeWorktreeGit(t, f.repo, "for-each-ref", "--format=%(refname):%(objectname)", "refs/heads") {
					t.Fatal("active hook rejection changed existing files or left a worktree/branch")
				}
			} else {
				body, err := os.ReadFile(filepath.Join(result, ".codex", "hooks.json"))
				if err != nil || !bytes.Equal(body, hooks) {
					t.Fatalf("disabled project hook copy changed: %v", err)
				}
				callInstructionsWorktreeHook(t, "WorktreeRemove", map[string]string{"worktree_path": result}, 0)
			}
		})
	}
}

func TestInstructionsWorktreeWithoutCodexBinary(t *testing.T) {
	for _, agent := range []string{"claude", "all"} {
		t.Run(agent, func(t *testing.T) {
			f := newNativeSetupFixture(t, true)
			setupNativeWorktree(t, f, agent)
			if agent == "all" {
				var stdout, stderr bytes.Buffer
				if code := runAgentInstructions([]string{"uninstall", f.repo, "--scope=repository", "--agent=codex"}, nil, &stdout, &stderr); code != 0 {
					t.Fatalf("disable Codex: exit=%d stdout=%s stderr=%s", code, &stdout, &stderr)
				}
			}
			git, err := exec.LookPath("git")
			if err != nil {
				t.Fatal(err)
			}
			bin := t.TempDir()
			if err := os.Symlink(git, filepath.Join(bin, "git")); err != nil {
				t.Fatal(err)
			}
			t.Setenv("PATH", bin)
			if _, err := exec.LookPath("codex"); err == nil {
				t.Fatal("Codex is still available")
			}
			target := callInstructionsWorktreeHook(t, "WorktreeCreate", map[string]string{"cwd": f.repo, "name": "claude-only"}, 0)
			body, err := os.ReadFile(filepath.Join(target, "CLAUDE.local.md"))
			if err != nil || !strings.HasSuffix(string(body), "\n\nprivate\n") {
				t.Fatalf("Claude local instructions missing: %q %v", body, err)
			}
			if _, err := os.Stat(filepath.Join(target, "AGENTS.override.md")); !os.IsNotExist(err) {
				t.Fatalf("disabled Codex document was created: %v", err)
			}
			callInstructionsWorktreeHook(t, "WorktreeRemove", map[string]string{"worktree_path": target}, 0)
		})
	}
}

func nativeWorktreeGit(t *testing.T, repo string, args ...string) string {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = repo
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %v: %v: %s", args, err, out)
	}
	return string(out)
}
