package agenthooks

var ghCommandOptions = map[string]map[string]optionValue{
	"":                           ghOptions(`--help --version`, ``),
	"agent-task":                 ghOptions(`--help`, ``),
	"agent-task create":          ghOptions(`--follow --help`, `-b --base -a --custom-agent -F --from-file -R --repo`),
	"agent-task list":            ghOptions(`-w --web --help`, `-q --jq --json -L --limit -t --template`),
	"agent-task view":            ghOptions(`--follow --log -w --web --help`, `-q --jq --json -R --repo -t --template`),
	"alias":                      ghOptions(`--help`, ``),
	"alias delete":               ghOptions(`--all --help`, ``),
	"alias import":               ghOptions(`--clobber --help`, ``),
	"alias list":                 ghOptions(`--help`, ``),
	"alias set":                  ghOptions(`--clobber -s --shell --help`, ``),
	"api":                        ghOptions(`-i --include --paginate --silent --slurp --verbose --help`, `--cache -F --field -H --header --hostname --input -q --jq -X --method -p --preview -f --raw-field -t --template`),
	"attestation":                ghOptions(`--help`, ``),
	"attestation download":       ghOptions(`--help`, `-d --digest-alg --hostname -L --limit -o --owner --predicate-type -R --repo`),
	"attestation trusted-root":   ghOptions(`--verify-only --help`, `--hostname --tuf-root --tuf-url`),
	"attestation verify":         ghOptions(`--bundle-from-oci --deny-self-hosted-runners --no-public-good --help`, `-b --bundle --cert-identity -i --cert-identity-regex --cert-oidc-issuer --custom-trusted-root -d --digest-alg --format --hostname -q --jq -L --limit -o --owner --predicate-type -R --repo --signer-digest --signer-repo --signer-workflow --source-digest --source-ref -t --template`),
	"auth":                       ghOptions(`--help`, ``),
	"auth login":                 ghOptions(`-c --clipboard --insecure-storage --skip-ssh-key -w --web --with-token --help`, `-p --git-protocol -h --hostname -s --scopes`),
	"auth logout":                ghOptions(`--help`, `-h --hostname -u --user`),
	"auth refresh":               ghOptions(`-c --clipboard --insecure-storage --reset-scopes --help`, `-h --hostname -r --remove-scopes -s --scopes`),
	"auth setup-git":             ghOptions(`-f --force --help`, `-h --hostname`),
	"auth status":                ghOptions(`-a --active -t --show-token --help`, `-h --hostname --jq --json --template`),
	"auth switch":                ghOptions(`--help`, `-h --hostname -u --user`),
	"auth token":                 ghOptions(`--help`, `-h --hostname -u --user`),
	"browse":                     optionValues(optionGroup{optionBooleanValue, `-a --actions --blame -n --no-browser -p --projects -r --releases -s --settings -w --wiki --help`}, optionGroup{optionRequiredValue, `-b --branch -R --repo`}, optionGroup{optionAttachedValue, `-c --commit`}),
	"cache":                      ghOptions(`--help`, `-R --repo`),
	"cache delete":               ghOptions(`-a --all --succeed-on-no-caches --help`, `-r --ref -R --repo`),
	"cache list":                 ghOptions(`--help`, `-q --jq --json -k --key -L --limit -O --order -r --ref -S --sort -t --template -R --repo`),
	"co":                         ghCheckoutOptions,
	"codespace":                  ghOptions(`--help`, ``),
	"codespace code":             ghOptions(`--insiders -w --web --help`, `-c --codespace -R --repo --repo-owner`),
	"codespace cp":               ghOptions(`-e --expand -r --recursive --help`, `-c --codespace -p --profile -R --repo --repo-owner`),
	"codespace create":           ghOptions(`--default-permissions -s --status -w --web --help`, `-b --branch --devcontainer-path -d --display-name --idle-timeout -l --location -m --machine -R --repo --retention-period`),
	"codespace delete":           ghOptions(`--all -f --force --help`, `-c --codespace --days -o --org -R --repo --repo-owner -u --user`),
	"codespace edit":             ghOptions(`--help`, `-c --codespace -d --display-name -m --machine -R --repo --repo-owner`),
	"codespace jupyter":          ghOptions(`--help`, `-c --codespace -R --repo --repo-owner`),
	"codespace list":             ghOptions(`-w --web --help`, `-q --jq --json -L --limit -o --org -R --repo -t --template -u --user`),
	"codespace logs":             ghOptions(`-f --follow --help`, `-c --codespace -R --repo --repo-owner`),
	"codespace ports":            ghOptions(`--help`, `-c --codespace -q --jq --json -R --repo --repo-owner -t --template`),
	"codespace ports forward":    ghOptions(`--help`, `-c --codespace -R --repo --repo-owner`),
	"codespace ports visibility": ghOptions(`--help`, `-c --codespace -R --repo --repo-owner`),
	"codespace rebuild":          ghOptions(`--full --help`, `-c --codespace -R --repo --repo-owner`),
	"codespace ssh":              ghOptions(`--config -d --debug --help`, `-c --codespace --debug-file --profile -R --repo --repo-owner --server-port`),
	"codespace stop":             ghOptions(`--help`, `-c --codespace -o --org -R --repo --repo-owner -u --user`),
	"codespace view":             ghOptions(`--help`, `-c --codespace -q --jq --json -R --repo --repo-owner -t --template`),
	"completion":                 ghOptions(`--help`, `-s --shell`),
	"config":                     ghOptions(`--help`, ``),
	"config clear-cache":         ghOptions(`--help`, ``),
	"config get":                 ghOptions(`--help`, `-h --host`),
	"config list":                ghOptions(`--help`, `-h --host`),
	"config set":                 ghOptions(`--help`, `-h --host`),
	"copilot":                    ghOptions(`--remove --help`, ``),
	"extension":                  ghOptions(`--help`, ``),
	"extension browse":           ghOptions(`--debug -s --single-column --help`, ``),
	"extension create":           ghOptions(`--help`, `--precompiled`),
	"extension exec":             ghOptions(`--help`, ``),
	"extension install":          ghOptions(`--force --help`, `--pin`),
	"extension list":             ghOptions(`--help`, ``),
	"extension remove":           ghOptions(`--help`, ``),
	"extension search":           ghOptions(`-w --web --help`, `-q --jq --json --license -L --limit --order --owner --sort -t --template`),
	"extension upgrade":          ghOptions(`--all --dry-run --force --help`, ``),
	"gist":                       ghOptions(`--help`, ``),
	"gist clone":                 ghOptions(`--help`, ``),
	"gist create":                ghOptions(`-p --public -w --web --help`, `-d --desc -f --filename`),
	"gist delete":                ghOptions(`--yes --help`, ``),
	"gist edit":                  ghOptions(`--help`, `-a --add -d --desc -f --filename -r --remove`),
	"gist list":                  ghOptions(`--include-content --public --secret --help`, `--filter -L --limit`),
	"gist rename":                ghOptions(`--help`, ``),
	"gist view":                  ghOptions(`--files -r --raw -w --web --help`, `-f --filename`),
	"gpg-key":                    ghOptions(`--help`, ``),
	"gpg-key add":                ghOptions(`--help`, `-t --title`),
	"gpg-key delete":             ghOptions(`-y --yes --help`, ``),
	"gpg-key list":               ghOptions(`--help`, ``),
	"help":                       ghOptions(`--help`, ``),
	"issue":                      ghOptions(`--help`, `-R --repo`),
	"issue close":                ghOptions(`--help`, `-c --comment --duplicate-of -r --reason -R --repo`),
	"issue comment":              ghOptions(`--create-if-none --delete-last --edit-last -e --editor -w --web --yes --help`, `-b --body -F --body-file -R --repo`),
	"issue create":               ghOptions(`-e --editor -w --web --help`, `-a --assignee -b --body -F --body-file -l --label -m --milestone -p --project --recover -T --template -t --title -R --repo`),
	"issue delete":               ghOptions(`--yes --help`, `-R --repo`),
	"issue develop":              ghOptions(`-c --checkout -l --list --help`, `-b --base --branch-repo -n --name -R --repo`),
	"issue edit":                 ghOptions(`--remove-milestone --help`, `--add-assignee --add-label --add-project -b --body -F --body-file -m --milestone --remove-assignee --remove-label --remove-project -t --title -R --repo`),
	"issue list":                 ghOptions(`-w --web --help`, `--app -a --assignee -A --author -q --jq --json -l --label -L --limit --mention -m --milestone -S --search -s --state -t --template -R --repo`),
	"issue lock":                 ghOptions(`--help`, `-r --reason -R --repo`),
	"issue pin":                  ghOptions(`--help`, `-R --repo`),
	"issue reopen":               ghOptions(`--help`, `-c --comment -R --repo`),
	"issue status":               ghOptions(`--help`, `-q --jq --json -t --template -R --repo`),
	"issue transfer":             ghOptions(`--help`, `-R --repo`),
	"issue unlock":               ghOptions(`--help`, `-R --repo`),
	"issue unpin":                ghOptions(`--help`, `-R --repo`),
	"issue view":                 ghOptions(`-c --comments -w --web --help`, `-q --jq --json -t --template -R --repo`),
	"label":                      ghOptions(`--help`, `-R --repo`),
	"label clone":                ghOptions(`-f --force --help`, `-R --repo`),
	"label create":               ghOptions(`-f --force --help`, `-c --color -d --description -R --repo`),
	"label delete":               ghOptions(`--yes --help`, `-R --repo`),
	"label edit":                 ghOptions(`--help`, `-c --color -d --description -n --name -R --repo`),
	"label list":                 ghOptions(`-w --web --help`, `-q --jq --json -L --limit --order -S --search --sort -t --template -R --repo`),
	"licenses":                   ghOptions(`--help`, ``),
	"org":                        ghOptions(`--help`, ``),
	"org list":                   ghOptions(`--help`, `-L --limit`),
	"pr":                         ghOptions(`--help`, `-R --repo`),
	"pr checkout":                ghCheckoutOptions,
	"pr checks":                  ghOptions(`--fail-fast --required --watch -w --web --help`, `-i --interval -q --jq --json -t --template -R --repo`),
	"pr close":                   ghOptions(`-d --delete-branch --help`, `-c --comment -R --repo`),
	"pr co":                      ghCheckoutOptions,
	"pr comment":                 ghOptions(`--create-if-none --delete-last --edit-last -e --editor -w --web --yes --help`, `-b --body -F --body-file -R --repo`),
	"pr create":                  ghOptions(`-d --draft --dry-run -e --editor -f --fill --fill-first --fill-verbose --no-maintainer-edit -w --web --help`, `-a --assignee -B --base -b --body -F --body-file -H --head -l --label -m --milestone -p --project --recover -r --reviewer -T --template -t --title -R --repo`),
	"pr diff":                    ghOptions(`--name-only --patch -w --web --help`, `--color -e --exclude -R --repo`),
	"pr edit":                    ghOptions(`--remove-milestone --help`, `--add-assignee --add-label --add-project --add-reviewer -B --base -b --body -F --body-file -m --milestone --remove-assignee --remove-label --remove-project --remove-reviewer -t --title -R --repo`),
	"pr list":                    ghOptions(`-d --draft -w --web --help`, `--app -a --assignee -A --author -B --base -H --head -q --jq --json -l --label -L --limit -S --search -s --state -t --template -R --repo`),
	"pr lock":                    ghOptions(`--help`, `-r --reason -R --repo`),
	"pr merge":                   ghOptions(`--admin --auto -d --delete-branch --disable-auto -m --merge -r --rebase -s --squash --help`, `-A --author-email -b --body -F --body-file --match-head-commit -t --subject -R --repo`),
	"pr ready":                   ghOptions(`--undo --help`, `-R --repo`),
	"pr reopen":                  ghOptions(`--help`, `-c --comment -R --repo`),
	"pr revert":                  ghOptions(`-d --draft --help`, `-b --body -F --body-file -t --title -R --repo`),
	"pr review":                  ghOptions(`-a --approve -c --comment -r --request-changes --help`, `-b --body -F --body-file -R --repo`),
	"pr status":                  ghOptions(`-c --conflict-status --help`, `-q --jq --json -t --template -R --repo`),
	"pr unlock":                  ghOptions(`--help`, `-R --repo`),
	"pr update-branch":           ghOptions(`--rebase --help`, `-R --repo`),
	"pr view":                    ghOptions(`-c --comments -w --web --help`, `-q --jq --json -t --template -R --repo`),
	"preview":                    ghOptions(`--help`, ``),
	"preview prompter":           ghOptions(`--help`, ``),
	"project":                    ghOptions(`--help`, ``),
	"project close":              ghOptions(`--undo --help`, `--format -q --jq --owner -t --template`),
	"project copy":               ghOptions(`--drafts --help`, `--format -q --jq --source-owner --target-owner -t --template --title`),
	"project create":             ghOptions(`--help`, `--format -q --jq --owner -t --template --title`),
	"project delete":             ghOptions(`--help`, `--format -q --jq --owner -t --template`),
	"project edit":               ghOptions(`--help`, `-d --description --format -q --jq --owner --readme -t --template --title --visibility`),
	"project field-create":       ghOptions(`--help`, `--data-type --format -q --jq --name --owner --single-select-options -t --template`),
	"project field-delete":       ghOptions(`--help`, `--format --id -q --jq -t --template`),
	"project field-list":         ghOptions(`--help`, `--format -q --jq -L --limit --owner -t --template`),
	"project item-add":           ghOptions(`--help`, `--format -q --jq --owner -t --template --url`),
	"project item-archive":       ghOptions(`--undo --help`, `--format --id -q --jq --owner -t --template`),
	"project item-create":        ghOptions(`--help`, `--body --format -q --jq --owner -t --template --title`),
	"project item-delete":        ghOptions(`--help`, `--format --id -q --jq --owner -t --template`),
	"project item-edit":          ghOptions(`--clear --help`, `--body --date --field-id --format --id --iteration-id -q --jq --number --project-id --single-select-option-id -t --template --text --title`),
	"project item-list":          ghOptions(`--help`, `--format -q --jq -L --limit --owner --query -t --template`),
	"project link":               ghOptions(`--help`, `--owner -R --repo -T --team`),
	"project list":               ghOptions(`--closed -w --web --help`, `--format -q --jq -L --limit --owner -t --template`),
	"project mark-template":      ghOptions(`--undo --help`, `--format -q --jq --owner -t --template`),
	"project unlink":             ghOptions(`--help`, `--owner -R --repo -T --team`),
	"project view":               ghOptions(`-w --web --help`, `--format -q --jq --owner -t --template`),
	"release":                    ghOptions(`--help`, `-R --repo`),
	"release create":             ghOptions(`-d --draft --fail-on-no-commits --generate-notes --latest --notes-from-tag -p --prerelease --verify-tag --help`, `--discussion-category -n --notes -F --notes-file --notes-start-tag --target -t --title -R --repo`),
	"release delete":             ghOptions(`--cleanup-tag -y --yes --help`, `-R --repo`),
	"release delete-asset":       ghOptions(`-y --yes --help`, `-R --repo`),
	"release download":           ghOptions(`--clobber --skip-existing --help`, `-A --archive -D --dir -O --output -p --pattern -R --repo`),
	"release edit":               ghOptions(`--draft --latest --prerelease --verify-tag --help`, `--discussion-category -n --notes -F --notes-file --tag --target -t --title -R --repo`),
	"release list":               ghOptions(`--exclude-drafts --exclude-pre-releases --help`, `-q --jq --json -L --limit -O --order -t --template -R --repo`),
	"release upload":             ghOptions(`--clobber --help`, `-R --repo`),
	"release verify":             ghOptions(`--help`, `--format -q --jq -t --template -R --repo`),
	"release verify-asset":       ghOptions(`--help`, `--format -q --jq -t --template -R --repo`),
	"release view":               ghOptions(`-w --web --help`, `-q --jq --json -t --template -R --repo`),
	"repo":                       ghOptions(`--help`, ``),
	"repo archive":               ghOptions(`-y --yes --help`, ``),
	"repo autolink":              ghOptions(`--help`, `-R --repo`),
	"repo autolink create":       ghOptions(`-n --numeric --help`, `-R --repo`),
	"repo autolink delete":       ghOptions(`--yes --help`, `-R --repo`),
	"repo autolink list":         ghOptions(`-w --web --help`, `-q --jq --json -t --template -R --repo`),
	"repo autolink view":         ghOptions(`--help`, `-q --jq --json -t --template -R --repo`),
	"repo clone":                 ghOptions(`--no-upstream --help`, `-u --upstream-remote-name`),
	"repo create":                ghOptions(`--add-readme -c --clone --disable-issues --disable-wiki --include-all-branches --internal --private --public --push --help`, `-d --description -g --gitignore -h --homepage -l --license -r --remote -s --source -t --team -p --template`),
	"repo delete":                ghOptions(`--yes --help`, ``),
	"repo deploy-key":            ghOptions(`--help`, `-R --repo`),
	"repo deploy-key add":        ghOptions(`-w --allow-write --help`, `-t --title -R --repo`),
	"repo deploy-key delete":     ghOptions(`--help`, `-R --repo`),
	"repo deploy-key list":       ghOptions(`--help`, `-q --jq --json -t --template -R --repo`),
	"repo edit":                  ghRepoEditOptions,
	"repo fork":                  ghOptions(`--clone --default-branch-only --remote --help`, `--fork-name --org --remote-name`),
	"repo gitignore":             ghOptions(`--help`, ``),
	"repo gitignore list":        ghOptions(`--help`, ``),
	"repo gitignore view":        ghOptions(`--help`, ``),
	"repo license":               ghOptions(`--help`, ``),
	"repo license list":          ghOptions(`--help`, ``),
	"repo license view":          ghOptions(`-w --web --help`, ``),
	"repo list":                  ghOptions(`--archived --fork --no-archived --source --help`, `-q --jq --json -l --language -L --limit -t --template --topic --visibility`),
	"repo rename":                ghOptions(`-y --yes --help`, `-R --repo`),
	"repo set-default":           ghOptions(`-u --unset -v --view --help`, ``),
	"repo sync":                  ghOptions(`--force --help`, `-b --branch -s --source`),
	"repo unarchive":             ghOptions(`-y --yes --help`, ``),
	"repo view":                  ghOptions(`-w --web --help`, `-b --branch -q --jq --json -t --template`),
	"ruleset":                    ghOptions(`--help`, `-R --repo`),
	"ruleset check":              ghOptions(`--default -w --web --help`, `-R --repo`),
	"ruleset list":               ghOptions(`-p --parents -w --web --help`, `-L --limit -o --org -R --repo`),
	"ruleset view":               ghOptions(`-p --parents -w --web --help`, `-o --org -R --repo`),
	"run":                        ghOptions(`--help`, `-R --repo`),
	"run cancel":                 ghOptions(`--force --help`, `-R --repo`),
	"run delete":                 ghOptions(`--help`, `-R --repo`),
	"run download":               ghOptions(`--help`, `-D --dir -n --name -p --pattern -R --repo`),
	"run list":                   ghOptions(`-a --all --help`, `-b --branch -c --commit --created -e --event -q --jq --json -L --limit -s --status -t --template -u --user -w --workflow -R --repo`),
	"run rerun":                  ghOptions(`-d --debug --failed --help`, `-j --job -R --repo`),
	"run view":                   ghOptions(`--exit-status --log --log-failed -v --verbose -w --web --help`, `-a --attempt -j --job -q --jq --json -t --template -R --repo`),
	"run watch":                  ghOptions(`--compact --exit-status --help`, `-i --interval -R --repo`),
	"search":                     ghOptions(`--help`, ``),
	"search code":                ghOptions(`-w --web --help`, `--extension --filename -q --jq --json --language -L --limit --match --owner -R --repo --size -t --template`),
	"search commits":             ghOptions(`--merge -w --web --help`, `--author --author-date --author-email --author-name --committer --committer-date --committer-email --committer-name --hash -q --jq --json -L --limit --order --owner --parent -R --repo --sort -t --template --tree --visibility`),
	"search issues":              ghOptions(`--archived --include-prs --locked --no-assignee --no-label --no-milestone --no-project -w --web --help`, `--app --assignee --author --closed --commenter --comments --created --interactions --involves -q --jq --json --label --language -L --limit --match --mentions --milestone --order --owner --project --reactions -R --repo --sort --state --team-mentions -t --template --updated --visibility`),
	"search prs":                 ghOptions(`--archived --draft --locked --merged --no-assignee --no-label --no-milestone --no-project -w --web --help`, `--app --assignee --author -B --base --checks --closed --commenter --comments --created -H --head --interactions --involves -q --jq --json --label --language -L --limit --match --mentions --merged-at --milestone --order --owner --project --reactions -R --repo --review --review-requested --reviewed-by --sort --state --team-mentions -t --template --updated --visibility`),
	"search repos":               ghOptions(`--archived -w --web --help`, `--created --followers --forks --good-first-issues --help-wanted-issues --include-forks -q --jq --json --language --license -L --limit --match --number-topics --order --owner --size --sort --stars -t --template --topic --updated --visibility`),
	"secret":                     ghOptions(`--help`, `-R --repo`),
	"secret delete":              ghOptions(`-u --user --help`, `-a --app -e --env -o --org -R --repo`),
	"secret list":                ghOptions(`-u --user --help`, `-a --app -e --env -q --jq --json -o --org -t --template -R --repo`),
	"secret set":                 ghOptions(`--no-repos-selected --no-store -u --user --help`, `-a --app -b --body -e --env -f --env-file -o --org -r --repos -v --visibility -R --repo`),
	"skill":                      ghOptions(`--help`, ``),
	"skill install":              ghOptions(`--allow-hidden-dirs -f --force --from-local --upstream --help`, `--agent --dir --pin --scope`),
	"skill preview":              ghOptions(`--allow-hidden-dirs --help`, ``),
	"skill publish":              ghOptions(`--dry-run --fix --help`, `--tag`),
	"skill search":               ghOptions(`--help`, `-q --jq --json -L --limit --owner --page -t --template`),
	"skill update":               ghOptions(`--all --dry-run --force --unpin --help`, `--dir`),
	"ssh-key":                    ghOptions(`--help`, ``),
	"ssh-key add":                ghOptions(`--help`, `-t --title --type`),
	"ssh-key delete":             ghOptions(`-y --yes --help`, ``),
	"ssh-key list":               ghOptions(`--help`, ``),
	"stack":                      ghOptions(`--help`, ``),
	"status":                     ghOptions(`--help`, `-e --exclude -o --org`),
	"variable":                   ghOptions(`--help`, `-R --repo`),
	"variable delete":            ghOptions(`--help`, `-e --env -o --org -R --repo`),
	"variable get":               ghOptions(`--help`, `-e --env -q --jq --json -o --org -t --template -R --repo`),
	"variable list":              ghOptions(`--help`, `-e --env -q --jq --json -o --org -t --template -R --repo`),
	"variable set":               ghOptions(`--help`, `-b --body -e --env -f --env-file -o --org -r --repos -v --visibility -R --repo`),
	"workflow":                   ghOptions(`--help`, `-R --repo`),
	"workflow disable":           ghOptions(`--help`, `-R --repo`),
	"workflow enable":            ghOptions(`--help`, `-R --repo`),
	"workflow list":              ghOptions(`-a --all --help`, `-q --jq --json -L --limit -t --template -R --repo`),
	"workflow run":               ghOptions(`--json --help`, `-F --field -f --raw-field -r --ref -R --repo`),
	"workflow view":              ghOptions(`-w --web -y --yaml --help`, `-r --ref -R --repo`),
	"alias ls":                   ghOptions(`--help`, ``),
	"cache ls":                   ghOptions(`--help`, `-q --jq --json -k --key -L --limit -O --order -r --ref -S --sort -t --template -R --repo`),
	"codespace ls":               ghOptions(`-w --web --help`, `-q --jq --json -L --limit -o --org -R --repo -t --template -u --user`),
	"config ls":                  ghOptions(`--help`, `-h --host`),
	"extension ls":               ghOptions(`--help`, ``),
	"gist ls":                    ghOptions(`--include-content --public --secret --help`, `--filter -L --limit`),
	"gpg-key ls":                 ghOptions(`--help`, ``),
	"issue ls":                   ghOptions(`-w --web --help`, `--app -a --assignee -A --author -q --jq --json -l --label -L --limit --mention -m --milestone -S --search -s --state -t --template -R --repo`),
	"label ls":                   ghOptions(`-w --web --help`, `-q --jq --json -L --limit --order -S --search --sort -t --template -R --repo`),
	"org ls":                     ghOptions(`--help`, `-L --limit`),
	"pr ls":                      ghOptions(`-d --draft -w --web --help`, `--app -a --assignee -A --author -B --base -H --head -q --jq --json -l --label -L --limit -S --search -s --state -t --template -R --repo`),
	"project ls":                 ghOptions(`--closed -w --web --help`, `--format -q --jq -L --limit --owner -t --template`),
	"release ls":                 ghOptions(`--exclude-drafts --exclude-pre-releases --help`, `-q --jq --json -L --limit -O --order -t --template -R --repo`),
	"repo autolink ls":           ghOptions(`-w --web --help`, `-q --jq --json -t --template -R --repo`),
	"repo deploy-key ls":         ghOptions(`--help`, `-q --jq --json -t --template -R --repo`),
	"repo gitignore ls":          ghOptions(`--help`, ``),
	"repo license ls":            ghOptions(`--help`, ``),
	"repo ls":                    ghOptions(`--archived --fork --no-archived --source --help`, `-q --jq --json -l --language -L --limit -t --template --topic --visibility`),
	"ruleset ls":                 ghOptions(`-p --parents -w --web --help`, `-L --limit -o --org -R --repo`),
	"run ls":                     ghOptions(`-a --all --help`, `-b --branch -c --commit --created -e --event -q --jq --json -L --limit -s --status -t --template -u --user -w --workflow -R --repo`),
	"secret ls":                  ghOptions(`-u --user --help`, `-a --app -e --env -q --jq --json -o --org -t --template -R --repo`),
	"ssh-key ls":                 ghOptions(`--help`, ``),
	"variable ls":                ghOptions(`--help`, `-e --env -q --jq --json -o --org -t --template -R --repo`),
	"workflow ls":                ghOptions(`-a --all --help`, `-q --jq --json -L --limit -t --template -R --repo`),
}

func ghOptions(booleans, values string) map[string]optionValue {
	return optionValues(optionGroup{optionBooleanValue, booleans}, optionGroup{optionRequiredValue, values})
}
