package agenthooks

import "fmt"

const (
	PresetGitHubHistoryGuard = "github-history-guard"

	PolicyGroupRemoteCodeRefMutation       = "remote-code-ref-mutation"
	PolicyGroupGitHubCollaborationMetadata = "github-collaboration-metadata"
	PolicyGroupLocalSystemSecretSafety     = "local-system-secret-safety"
)

func Preset(id string) (Policy, error) {
	switch id {
	case PresetGitHubHistoryGuard:
		return githubHistoryGuardPreset(), nil
	default:
		return Policy{}, fmt.Errorf("unknown preset %q", id)
	}
}

func githubHistoryGuardPreset() Policy {
	policy := Policy{
		Version:     PolicyVersion,
		ID:          PresetGitHubHistoryGuard,
		Description: "Allow GitHub PR/issue collaboration while blocking code history, repository state, destructive local, privilege escalation, and token exposure commands.",
		Enabled:     true,
		Groups: []Group{
			{
				ID:          PolicyGroupRemoteCodeRefMutation,
				Description: "Blocks commands that can push, publish, rewrite, move, merge, or hide code history, refs, tags, releases, PR branch state, or repository state.",
			},
			{
				ID:          PolicyGroupLocalSystemSecretSafety,
				Description: "Blocks local destructive, formatting, privilege escalation, system control, broad process kill, permission ownership change, and token disclosure commands.",
			},
			{
				ID:          PolicyGroupGitHubCollaborationMetadata,
				Description: "Allows PR/Issue text, comment, review metadata, and PR stack links that do not push or move refs.",
			},
		},
		Rules: []Rule{
			{
				ID:      "deny-git-push",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "push")},
				Message: "git push changes remote history or published refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-send-pack",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "send-pack")},
				Message: "git send-pack changes remote refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-http-push",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "http-push")},
				Message: "git http-push changes remote refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-pull",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "pull")},
				Message: "git pull can merge or move the current branch; use git fetch or get explicit approval.",
			},
			{
				ID:      "deny-git-merge",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "merge")},
				Message: "git merge changes code history; get explicit approval first.",
			},
			{
				ID:      "deny-git-rebase",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "rebase")},
				Message: "git rebase rewrites code history; get explicit approval first.",
			},
			{
				ID:      "deny-git-filter-branch",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "filter-branch")},
				Message: "git filter-branch rewrites repository history; get explicit approval first.",
			},
			{
				ID:      "deny-git-hook",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "hook")},
				Message: "git hook run executes .git/hooks scripts the policy evaluator cannot see; get explicit approval first.",
			},
			{
				ID:      "deny-git-for-each-repo",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "for-each-repo")},
				Message: "git for-each-repo runs an arbitrary git command in configured repositories; get explicit approval first.",
			},
			{
				ID:      "deny-git-bisect-run",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "bisect", "run")},
				Message: "git bisect run executes another command outside the visible policy decision; get explicit approval first.",
			},
			{
				ID:      "deny-git-submodule-foreach",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "submodule", "foreach")},
				Message: "git submodule foreach executes another command in submodules; get explicit approval first.",
			},
			{
				ID:      "deny-git-update-ref",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "update-ref")},
				Message: "git update-ref changes refs directly; get explicit approval first.",
			},
			{
				ID:      "deny-git-replace",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "replace")},
				Message: "git replace changes repository object replacement refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-reflog-expire",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "reflog", "expire")},
				Message: "git reflog expire removes recovery history; get explicit approval first.",
			},
			{
				ID:      "deny-git-branch-force",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "branch"), HasFlag: []string{"-f"}},
				Message: "git branch --force moves refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-branch-force-long",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "branch"), HasFlag: []string{"--force"}},
				Message: "git branch --force moves refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-branch-delete",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "branch"), HasFlag: []string{"-d"}},
				Message: "git branch delete changes refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-branch-delete-force",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "branch"), HasFlag: []string{"-D"}},
				Message: "git branch delete changes refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-branch-delete-long",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "branch"), HasFlag: []string{"--delete"}},
				Message: "git branch delete changes refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-branch-move",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "branch"), HasFlag: []string{"-m"}},
				Message: "git branch move changes refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-branch-move-force",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "branch"), HasFlag: []string{"-M"}},
				Message: "git branch move changes refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-branch-move-long",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "branch"), HasFlag: []string{"--move"}},
				Message: "git branch move changes refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-branch-copy",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "branch"), HasFlag: []string{"-c"}},
				Message: "git branch copy changes refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-branch-copy-force",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "branch"), HasFlag: []string{"-C"}},
				Message: "git branch copy changes refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-branch-copy-long",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "branch"), HasFlag: []string{"--copy"}},
				Message: "git branch copy changes refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-switch-force-create",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "switch"), HasFlag: []string{"-C"}},
				Message: "git switch --force-create resets branch refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-switch-force-create-long",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "switch"), HasFlag: []string{"--force-create"}},
				Message: "git switch --force-create resets branch refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-checkout-force-create",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "checkout"), HasFlag: []string{"-B"}},
				Message: "git checkout -B resets branch refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-tag-force",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "tag"), HasFlag: []string{"-f"}},
				Message: "git tag --force changes tag refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-tag-force-long",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "tag"), HasFlag: []string{"--force"}},
				Message: "git tag --force changes tag refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-tag-delete",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "tag"), HasFlag: []string{"-d"}},
				Message: "git tag delete changes tag refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-tag-delete-long",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "tag"), HasFlag: []string{"--delete"}},
				Message: "git tag delete changes tag refs; get explicit approval first.",
			},
			{
				ID:      "deny-git-config-alias",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "config"), Contains: []ArgPattern{{Glob: "alias.*", Fold: true}}},
				Message: "git config alias changes can hide protected git commands; get explicit approval first.",
			},
			{
				ID:      "deny-git-config-include",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "config"), Contains: []ArgPattern{{Glob: "include.*", Fold: true}}},
				Message: "git config include changes can hide protected git commands; get explicit approval first.",
			},
			{
				ID:      "deny-git-config-includeif",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "config"), Contains: []ArgPattern{{Glob: "includeif.*", Fold: true}}},
				Message: "git config includeIf changes can hide protected git commands; get explicit approval first.",
			},
			{
				ID:      "deny-git-commit-amend",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "commit"), HasFlag: []string{"--amend"}},
				Message: "git commit --amend rewrites commit history; create a new commit or get explicit approval.",
			},
			{
				ID:      "deny-git-reset-hard",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("git", "reset"), HasFlag: []string{"--hard"}},
				Message: "git reset --hard can destroy local work; get explicit approval first.",
			},
			{
				ID:      "deny-rm",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("rm")},
				Message: "rm can delete local work; use trash or get explicit approval first.",
			},
			{
				ID:      "deny-rmdir",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("rmdir")},
				Message: "rmdir can delete local directories; use trash or get explicit approval first.",
			},
			{
				ID:      "deny-unlink",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("unlink")},
				Message: "unlink can delete local files; use trash or get explicit approval first.",
			},
			{
				ID:      "deny-mkfs-family",
				Effect:  EffectDeny,
				Match:   Match{Argv: []ArgPattern{{Glob: "mkfs*"}}},
				Message: "mkfs formatting commands can destroy filesystems; get explicit approval first.",
			},
			{
				ID:      "deny-newfs-family",
				Effect:  EffectDeny,
				Match:   Match{Argv: []ArgPattern{{Glob: "newfs*"}}},
				Message: "newfs formatting commands can destroy filesystems; get explicit approval first.",
			},
			{
				ID:      "deny-fdisk",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("fdisk")},
				Message: "fdisk changes disk partition state; get explicit approval first.",
			},
			{
				ID:      "deny-dd-input",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("dd"), Contains: []ArgPattern{{Glob: "if=*"}}},
				Message: "dd with an explicit input can copy raw device or file contents; get explicit approval first.",
			},
			{
				ID:      "deny-dd-output",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("dd"), Contains: []ArgPattern{{Glob: "of=*"}}},
				Message: "dd with an explicit output can overwrite raw devices or files; get explicit approval first.",
			},
			{
				ID:      "deny-sudo",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("sudo")},
				Message: "sudo runs with elevated privileges; get explicit approval first.",
			},
			{
				ID:      "deny-doas",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("doas")},
				Message: "doas runs with elevated privileges; get explicit approval first.",
			},
			{
				ID:      "deny-su",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("su")},
				Message: "su changes user privileges; get explicit approval first.",
			},
			{
				ID:      "deny-shutdown",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("shutdown")},
				Message: "shutdown changes system state; get explicit approval first.",
			},
			{
				ID:      "deny-reboot",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("reboot")},
				Message: "reboot changes system state; get explicit approval first.",
			},
			{
				ID:      "deny-poweroff",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("poweroff")},
				Message: "poweroff changes system state; get explicit approval first.",
			},
			{
				ID:      "deny-halt",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("halt")},
				Message: "halt changes system state; get explicit approval first.",
			},
			{
				ID:      "deny-init-stop",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("init", "0"), Exact: true},
				Message: "init 0 changes system state; get explicit approval first.",
			},
			{
				ID:      "deny-init-reboot",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("init", "6"), Exact: true},
				Message: "init 6 changes system state; get explicit approval first.",
			},
			{
				ID:      "deny-killall",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("killall")},
				Message: "killall terminates processes by name; get explicit approval first.",
			},
			{
				ID:      "deny-pkill",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("pkill")},
				Message: "pkill terminates processes by pattern; get explicit approval first.",
			},
			{
				ID:      "deny-kill-multiple-pids",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("kill"), Risk: riskKillMultiplePIDs},
				Message: "kill with multiple PID operands can terminate broad process sets; get explicit approval first.",
			},
			{
				ID:      "deny-kill-multiple-pids-with-signal",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("kill"), Risk: riskKillMultiplePIDsWithSignal},
				Message: "kill with multiple PID operands can terminate broad process sets; get explicit approval first.",
			},
			{
				ID:      "deny-kill-zero-pid",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("kill"), Risk: riskKillZeroPID},
				Message: "kill with PID 0 targets the caller process group; get explicit approval first.",
			},
			{
				ID:      "deny-kill-negative-pid",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("kill"), Risk: riskKillNegativePID},
				Message: "kill with a negative PID can target process groups; get explicit approval first.",
			},
			{
				ID:      "deny-kill-negative-pid-after-end",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("kill"), Risk: riskKillNegativePIDAfterEnd},
				Message: "kill with a negative PID can target process groups; get explicit approval first.",
			},
			{
				ID:      "deny-chmod",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("chmod")},
				Message: "chmod changes file permissions; get explicit approval first.",
			},
			{
				ID:      "deny-chown",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("chown")},
				Message: "chown changes file ownership; get explicit approval first.",
			},
			{
				ID:      "deny-chgrp",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("chgrp")},
				Message: "chgrp changes file group ownership; get explicit approval first.",
			},
			{
				ID:      "deny-gh-auth-token",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "auth", "token")},
				Message: "gh auth token can print an authentication token; get explicit approval first.",
			},
			{
				ID:      "deny-gh-auth-status-token-long",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "auth", "status"), HasFlag: []string{"--show-token"}},
				Message: "gh auth status --show-token can print an authentication token; get explicit approval first.",
			},
			{
				ID:      "deny-gh-auth-status-token-short",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "auth", "status"), HasFlag: []string{"-t"}},
				Message: "gh auth status -t can print an authentication token; get explicit approval first.",
			},
			{
				ID:      "deny-gh-pr-merge",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "pr", "merge")},
				Message: "gh pr merge changes repository history on GitHub; get explicit approval first.",
			},
			{
				ID:      "deny-gh-pr-update-branch",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "pr", "update-branch")},
				Message: "gh pr update-branch changes PR branch history; get explicit approval first.",
			},
			{
				ID:      "deny-gh-issue-develop",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "issue", "develop")},
				Message: "gh issue develop can create or link a branch for an issue; get explicit approval first.",
			},
			{
				ID:      "deny-gh-pr-revert",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "pr", "revert")},
				Message: "gh pr revert can create revert source and a PR branch; get explicit approval first.",
			},
			{
				ID:     "deny-gh-pr-create-without-head",
				Effect: EffectDeny,
				Match:  Match{Argv: exactArgs("gh", "pr", "create")},
				Except: []Match{
					{Argv: exactArgs("gh", "pr", "create"), HasFlag: []string{"--head"}},
					{Argv: exactArgs("gh", "pr", "create"), HasFlag: []string{"-H"}},
				},
				Message: "gh pr create may push the current branch unless --head is supplied; use --head for push-free PR metadata work.",
			},
			{
				ID:      "deny-gh-pr-close-delete-branch",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "pr", "close"), HasFlag: []string{"--delete-branch"}},
				Message: "gh pr close --delete-branch deletes the PR branch ref; get explicit approval first.",
			},
			{
				ID:      "deny-gh-pr-close-delete-branch-short",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "pr", "close"), HasFlag: []string{"-d"}},
				Message: "gh pr close -d deletes the PR branch ref; get explicit approval first.",
			},
			{
				ID:      "deny-gh-pr-checkout-force",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "pr", "checkout"), HasFlag: []string{"--force"}},
				Message: "gh pr checkout --force resets local branch state; get explicit approval first.",
			},
			{
				ID:      "deny-gh-pr-checkout-force-short",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "pr", "checkout"), HasFlag: []string{"-f"}},
				Message: "gh pr checkout --force resets local branch state; get explicit approval first.",
			},
			{
				ID:      "deny-gh-pr-co-force",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "pr", "co"), HasFlag: []string{"--force"}},
				Message: "gh pr co --force resets local branch state; get explicit approval first.",
			},
			{
				ID:      "deny-gh-pr-co-force-short",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "pr", "co"), HasFlag: []string{"-f"}},
				Message: "gh pr co --force resets local branch state; get explicit approval first.",
			},
			{
				ID:      "deny-gh-co-force",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "co"), HasFlag: []string{"--force"}},
				Message: "gh co --force resets local branch state; get explicit approval first.",
			},
			{
				ID:      "deny-gh-co-force-short",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "co"), HasFlag: []string{"-f"}},
				Message: "gh co --force resets local branch state; get explicit approval first.",
			},
			{
				ID:      "deny-gh-repo-visibility",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "repo", "edit"), HasFlag: []string{"--visibility"}},
				Message: "repository visibility changes require explicit approval.",
			},
			{
				ID:      "deny-gh-repo-sync",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "repo", "sync")},
				Message: "gh repo sync changes repository refs; get explicit approval first.",
			},
			{
				ID:      "deny-gh-repo-create",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "repo", "create")},
				Message: "gh repo create creates remote repository state and can publish source; get explicit approval first.",
			},
			{
				ID:      "deny-gh-repo-delete",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "repo", "delete")},
				Message: "gh repo delete removes a remote repository and its source history; get explicit approval first.",
			},
			{
				ID:      "deny-gh-repo-fork",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "repo", "fork")},
				Message: "gh repo fork creates a remote repository copy; get explicit approval first.",
			},
			{
				ID:      "deny-gh-repo-deploy-key-add-write",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "repo", "deploy-key", "add"), HasFlag: []string{"--allow-write"}},
				Message: "gh repo deploy-key add --allow-write grants future remote write access; get explicit approval first.",
			},
			{
				ID:      "deny-gh-repo-deploy-key-add-write-short",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "repo", "deploy-key", "add"), HasFlag: []string{"-w"}},
				Message: "gh repo deploy-key add -w grants future remote write access; get explicit approval first.",
			},
			{
				ID:      "deny-gh-release-create",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "release", "create")},
				Message: "gh release create can create tags or publish repository state; get explicit approval first.",
			},
			{
				ID:      "deny-gh-release-edit",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "release", "edit")},
				Message: "gh release edit changes published release state; get explicit approval first.",
			},
			{
				ID:      "deny-gh-release-upload",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "release", "upload")},
				Message: "gh release upload changes published release assets; get explicit approval first.",
			},
			{
				ID:      "deny-gh-release-delete-asset",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "release", "delete-asset")},
				Message: "gh release delete-asset removes published release assets; get explicit approval first.",
			},
			{
				ID:      "deny-gh-release-delete",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "release", "delete")},
				Message: "gh release delete can remove release or tag state; get explicit approval first.",
			},
			{
				ID:      "deny-gh-api",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "api")},
				Message: "raw gh api calls are blocked by this preset; use explicit PR/issue commands or get approval.",
			},
			{
				ID:      "deny-gh-alias-set",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "alias", "set")},
				Message: "gh alias changes can hide protected GitHub commands; get explicit approval first.",
			},
			{
				ID:      "deny-gh-alias-import",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "alias", "import")},
				Message: "gh alias changes can hide protected GitHub commands; get explicit approval first.",
			},
			{
				ID:      "deny-gh-alias-delete",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "alias", "delete")},
				Message: "gh alias changes can hide protected GitHub commands; get explicit approval first.",
			},
			{
				ID:      "deny-gh-extension-exec",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "extension", "exec")},
				Message: "gh extension exec hides GitHub operations from the policy evaluator; get explicit approval first.",
			},
			{
				ID:      "deny-gh-workflow-run",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "workflow", "run")},
				Message: "gh workflow run starts remote automation that can change repository state; get explicit approval first.",
			},
			{
				ID:      "deny-gh-run-rerun",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "run", "rerun")},
				Message: "gh run rerun restarts remote automation that can change repository state; get explicit approval first.",
			},
			{
				ID:      "deny-gh-agent-task-create",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "agent-task", "create")},
				Message: "gh agent-task create dispatches a remote coding agent that can change repository state; get explicit approval first.",
			},
			{
				ID:      "deny-gh-codespace-ssh",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("gh", "codespace", "ssh")},
				Message: "gh codespace ssh can run commands outside the visible local policy decision; get explicit approval first.",
			},
			{
				ID:      "deny-shell-alias",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("alias")},
				Message: "shell alias changes can hide protected commands; get explicit approval first.",
			},
			{
				ID:      "deny-shell-source",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("source")},
				Message: "source executes script content that is not visible to the policy evaluator; get explicit approval first.",
			},
			{
				ID:      "deny-shell-dot-source",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs(".")},
				Message: ". executes script content that is not visible to the policy evaluator; get explicit approval first.",
			},
			{
				ID:      "deny-shell-trap",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("trap")},
				Message: "trap can defer protected commands outside visible execution order; get explicit approval first.",
			},
			{
				ID:      "deny-shell-xargs",
				Effect:  EffectDeny,
				Match:   Match{Argv: exactArgs("xargs")},
				Message: "xargs builds command arguments from hidden input; get explicit approval first.",
			},
			{
				ID:     "deny-gh-stack-except-link-two-ints",
				Effect: EffectDeny,
				Match:  Match{Argv: exactArgs("gh", "stack")},
				Except: []Match{{
					Argv:  []ArgPattern{{Exact: "gh"}, {Exact: "stack"}, {Exact: "link"}, {Type: "int"}, {Type: "int"}},
					Exact: true,
				}},
				Message: "gh stack link is only allowed as: gh stack link <number> <number>.",
			},
		},
		Tests: []TestCase{
			{Name: "allow pr create with explicit head", Command: `gh pr create --head feature --title "change" --body "body"`, Want: DecisionAllow},
			{Name: "allow issue create", Command: `gh issue create --title "bug" --body "body"`, Want: DecisionAllow},
			{Name: "allow pr edit", Command: `gh pr edit 12 --body-file body.md`, Want: DecisionAllow},
			{Name: "allow pr comment", Command: `gh pr comment 12 --body "looks good"`, Want: DecisionAllow},
			{Name: "allow issue comment", Command: `gh issue comment 12 --body "needs info"`, Want: DecisionAllow},
			{Name: "allow issue edit", Command: `gh issue edit 12 --body-file body.md`, Want: DecisionAllow},
			{Name: "allow issue view", Command: `gh issue view 12`, Want: DecisionAllow},
			{Name: "allow pr close without branch delete", Command: `gh pr close 12 --comment "not ready"`, Want: DecisionAllow},
			{Name: "deny pr create without explicit head", Command: `gh pr create --title "change" --body "body"`, Want: DecisionDeny, RuleID: "deny-gh-pr-create-without-head"},
			{Name: "deny git push", Command: `git push origin main`, Want: DecisionDeny, RuleID: "deny-git-push"},
			{Name: "deny absolute git push", Command: `/usr/bin/git push origin main`, Want: DecisionDeny, RuleID: "deny-git-push"},
			{Name: "deny dashed git push helper", Command: `/usr/libexec/git-core/git-push origin main`, Want: DecisionDeny, RuleID: "deny-git-push"},
			{Name: "deny git send pack", Command: `git send-pack origin refs/heads/main`, Want: DecisionDeny, RuleID: "deny-git-send-pack"},
			{Name: "deny dashed git send pack helper", Command: `/usr/libexec/git-core/git-send-pack origin refs/heads/main`, Want: DecisionDeny, RuleID: "deny-git-send-pack"},
			{Name: "deny git http push", Command: `git http-push origin refs/heads/main`, Want: DecisionDeny, RuleID: "deny-git-http-push"},
			{Name: "deny dashed git http push helper", Command: `/usr/libexec/git-core/git-http-push origin refs/heads/main`, Want: DecisionDeny, RuleID: "deny-git-http-push"},
			{Name: "deny git push with worktree option", Command: `git -C . push origin main`, Want: DecisionDeny, RuleID: "deny-git-push"},
			{Name: "deny git push with config option", Command: `git -c core.hooksPath=/tmp/hooks push origin main`, Want: DecisionDeny, RuleID: "deny-git-push"},
			{Name: "deny git push with latest global option", Command: `git --no-advice --no-lazy-fetch push origin main`, Want: DecisionDeny, RuleID: "deny-git-push"},
			{Name: "deny git exec path dispatch", Command: `git --exec-path=/tmp x origin main`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny git exec path dispatch split", Command: `git --exec-path /tmp x origin main`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny git exec path env dispatch", Command: `GIT_EXEC_PATH=/tmp git x origin main`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny env git exec path dispatch", Command: `env GIT_EXEC_PATH=/tmp git x origin main`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny git alias config", Command: `git -c alias.x=push x origin main`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny git config-env alias", Command: `git --config-env alias.x=GIT_ALIAS_VALUE x origin main`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny git config env assignment alias", Command: `GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=alias.x GIT_CONFIG_VALUE_0=push git x origin main`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny env git config alias", Command: `env GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=alias.x GIT_CONFIG_VALUE_0=push git x origin main`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny brace expansion git command", Command: `g{i..i}t push origin main`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny brace comma expansion git command", Command: `g{i,j}it push origin main`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny quoted split brace git command", Command: `{g'it',} push origin main`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny double quoted split brace git command", Command: `{g"it",} push origin main`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "allow reflog selector with quoted path", Command: `git show HEAD@{u}:'docs/My File.md'`, Want: DecisionAllow},
			{Name: "allow git show reflog selector", Command: `git show HEAD@{u}`, Want: DecisionAllow},
			{Name: "allow git stash drop reflog selector", Command: `git stash drop stash@{0}`, Want: DecisionAllow},
			{Name: "deny glob git command", Command: `/usr/bin/g[i]t push origin main`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny dynamic glob arg for protected git (intended fail-closed)", Command: `git add *.go`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny unknown git alias dispatch", Command: `git ship origin main`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny unknown git alias dispatch with home", Command: `HOME=/tmp/quota-test-home git ship origin main`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny unknown dashed git helper", Command: `/usr/libexec/git-core/git-ship origin main`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny command path git push", Command: `command -p git push origin main`, Want: DecisionDeny, RuleID: "deny-git-push"},
			{Name: "deny command separator git push", Command: `command -- git push origin main`, Want: DecisionDeny, RuleID: "deny-git-push"},
			{Name: "deny exec alternate name git push", Command: `exec -a marker git push origin main`, Want: DecisionDeny, RuleID: "deny-git-push"},
			{Name: "deny env wrapped git push", Command: `env GIT_TRACE=1 git push origin main`, Want: DecisionDeny, RuleID: "deny-git-push"},
			{Name: "deny env path wrapped git push", Command: `env -P /usr/bin git push origin main`, Want: DecisionDeny, RuleID: "deny-git-push"},
			{Name: "deny env inline path wrapped git push", Command: `env -P/usr/bin git push origin main`, Want: DecisionDeny, RuleID: "deny-git-push"},
			{Name: "deny env inline unset wrapped git push", Command: `env -uPATH git push origin main`, Want: DecisionDeny, RuleID: "deny-git-push"},
			{Name: "deny env grouped unset wrapped git push", Command: `env -iuPATH git push origin main`, Want: DecisionDeny, RuleID: "deny-git-push"},
			{Name: "deny sudo env assignment wrapped git push", Command: `sudo FOO=bar git push origin main`, Want: DecisionDeny, RuleID: "deny-sudo"},
			{Name: "deny sudo chdir wrapped git push", Command: `sudo -D /tmp git push origin main`, Want: DecisionDeny, RuleID: "deny-sudo"},
			{Name: "deny sudo inline user wrapped git push", Command: `sudo -unobody git push origin main`, Want: DecisionDeny, RuleID: "deny-sudo"},
			{Name: "deny env split git push", Command: `env -S 'git push origin main'`, Want: DecisionDeny, RuleID: "deny-git-push"},
			{Name: "deny env inline split git push", Command: `env -Sgit\ push\ origin\ main`, Want: DecisionDeny, RuleID: "deny-git-push"},
			{Name: "deny env combined split git push", Command: `env -iS 'git push origin main'`, Want: DecisionDeny, RuleID: "deny-git-push"},
			{Name: "deny env combined inline split git push", Command: `env -iSgit\ push\ origin\ main`, Want: DecisionDeny, RuleID: "deny-git-push"},
			{Name: "deny eval git push", Command: `eval 'git push origin main'`, Want: DecisionDeny, RuleID: "deny-git-push"},
			{Name: "deny shell stdin git push", Command: `printf 'git push origin main\n' | sh`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny shell heredoc git push", Command: "bash <<'EOF'\ngit push origin main\nEOF", Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny shell nested git push", Command: `sh -c 'git push origin main'`, Want: DecisionDeny, RuleID: "deny-git-push"},
			{Name: "deny shell option nested git push", Command: `bash -O extglob -c 'git push origin main'`, Want: DecisionDeny, RuleID: "deny-git-push"},
			{Name: "deny bash startup env hidden script", Command: `BASH_ENV=/tmp/quota-hook-policy bash -c true`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny env bash startup hidden script", Command: `env BASH_ENV=/tmp/quota-hook-policy bash -c true`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny sudo bash startup hidden script", Command: `sudo BASH_ENV=/tmp/quota-hook-policy bash -c true`, Want: DecisionDeny, RuleID: "deny-sudo"},
			{Name: "deny shell rcfile hidden script", Command: `bash --rcfile /tmp/quota-hook-policy -ic true`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny shell init file hidden script", Command: `bash --init-file=/tmp/quota-hook-policy -ic true`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny interactive bash hidden startup", Command: `bash -ic 'gp origin main'`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny interactive zsh hidden startup", Command: `zsh -ic 'gp origin main'`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny login bash hidden startup", Command: `bash -lc 'gp origin main'`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny login zsh hidden startup", Command: `zsh -lc 'gp origin main'`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny long login shell hidden startup", Command: `bash --login -c 'gp origin main'`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny exec login shell hidden startup", Command: `exec -l bash -c 'gp origin main'`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny exec alternate login shell hidden startup", Command: `exec -a -bash bash -c 'gp origin main'`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny command exec login shell hidden startup", Command: `command exec -l bash -c 'gp origin main'`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny sudo login shell hidden startup", Command: `sudo -i bash -c 'gp origin main'`, Want: DecisionDeny, RuleID: "deny-sudo"},
			{Name: "allow shell norc visible script", Command: `bash --norc -c true`, Want: DecisionAllow},
			{Name: "deny shell norc script file", Command: `bash --norc /tmp/quota-hook-policy`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "allow shell version", Command: `bash --version`, Want: DecisionAllow},
			{Name: "deny git pull", Command: `git pull --ff-only`, Want: DecisionDeny, RuleID: "deny-git-pull"},
			{Name: "deny git merge", Command: `git merge feature`, Want: DecisionDeny, RuleID: "deny-git-merge"},
			{Name: "deny git rebase", Command: `git rebase main`, Want: DecisionDeny, RuleID: "deny-git-rebase"},
			{Name: "deny git filter branch", Command: `git filter-branch -- --all`, Want: DecisionDeny, RuleID: "deny-git-filter-branch"},
			{Name: "deny git hook run", Command: `git hook run pre-push`, Want: DecisionDeny, RuleID: "deny-git-hook"},
			{Name: "deny git for-each-repo", Command: `git -c audit.repos=/example/repo for-each-repo --config=audit.repos push origin main`, Want: DecisionDeny, RuleID: "deny-git-for-each-repo"},
			{Name: "deny git bisect run", Command: `git bisect run ./try-build.sh`, Want: DecisionDeny, RuleID: "deny-git-bisect-run"},
			{Name: "deny git submodule foreach", Command: `git submodule foreach ./publish.sh`, Want: DecisionDeny, RuleID: "deny-git-submodule-foreach"},
			{Name: "deny git commit dashdash as message value", Command: `git commit -m -- --amend`, Want: DecisionDeny, RuleID: "deny-git-commit-amend"},
			{Name: "deny git update ref", Command: `git update-ref -d refs/heads/main`, Want: DecisionDeny, RuleID: "deny-git-update-ref"},
			{Name: "deny dashed git update ref helper", Command: `/usr/libexec/git-core/git-update-ref -d refs/heads/main`, Want: DecisionDeny, RuleID: "deny-git-update-ref"},
			{Name: "deny git replace", Command: `git replace -f old new`, Want: DecisionDeny, RuleID: "deny-git-replace"},
			{Name: "deny git reflog expire", Command: `git reflog expire --expire=now --all`, Want: DecisionDeny, RuleID: "deny-git-reflog-expire"},
			{Name: "deny git branch force", Command: `git branch -f main HEAD~1`, Want: DecisionDeny, RuleID: "deny-git-branch-force"},
			{Name: "deny git branch grouped delete force", Command: `git branch -df feature`, Want: DecisionDeny, RuleID: "deny-git-branch-force"},
			{Name: "deny git branch force abbreviation", Command: `git branch --forc main HEAD~1`, Want: DecisionDeny, RuleID: "deny-git-branch-force-long"},
			{Name: "deny git branch delete force", Command: `git branch -D feature`, Want: DecisionDeny, RuleID: "deny-git-branch-delete-force"},
			{Name: "deny git branch delete long", Command: `git branch --delete feature`, Want: DecisionDeny, RuleID: "deny-git-branch-delete-long"},
			{Name: "deny git branch move force", Command: `git branch -M old new`, Want: DecisionDeny, RuleID: "deny-git-branch-move-force"},
			{Name: "deny git branch move long", Command: `git branch --move old new`, Want: DecisionDeny, RuleID: "deny-git-branch-move-long"},
			{Name: "deny git branch copy force", Command: `git branch -C old new`, Want: DecisionDeny, RuleID: "deny-git-branch-copy-force"},
			{Name: "deny git branch copy long", Command: `git branch --copy old new`, Want: DecisionDeny, RuleID: "deny-git-branch-copy-long"},
			{Name: "deny git switch force create", Command: `git switch -C main HEAD~1`, Want: DecisionDeny, RuleID: "deny-git-switch-force-create"},
			{Name: "deny git checkout force create", Command: `git checkout -B main HEAD~1`, Want: DecisionDeny, RuleID: "deny-git-checkout-force-create"},
			{Name: "deny git tag force", Command: `git tag -f v1 HEAD~1`, Want: DecisionDeny, RuleID: "deny-git-tag-force"},
			{Name: "deny git config alias", Command: `git config alias.x push`, Want: DecisionDeny, RuleID: "deny-git-config-alias"},
			{Name: "deny git config alias mixed case", Command: `git config Alias.x push`, Want: DecisionDeny, RuleID: "deny-git-config-alias"},
			{Name: "deny git config include", Command: `git config include.path ../config`, Want: DecisionDeny, RuleID: "deny-git-config-include"},
			{Name: "deny git config include mixed case", Command: `git config Include.path ../config`, Want: DecisionDeny, RuleID: "deny-git-config-include"},
			{Name: "deny git config includeIf", Command: `git config includeIf.onbranch:main.path ../config`, Want: DecisionDeny, RuleID: "deny-git-config-includeif"},
			{Name: "deny git config includeif lowercase", Command: `git config includeif.onbranch:main.path ../config`, Want: DecisionDeny, RuleID: "deny-git-config-includeif"},
			{Name: "deny git amend", Command: `git commit --amend -m change`, Want: DecisionDeny, RuleID: "deny-git-commit-amend"},
			{Name: "deny git amend abbreviation", Command: `git commit --amen --dry-run`, Want: DecisionDeny, RuleID: "deny-git-commit-amend"},
			{Name: "allow normal git commit", Command: `git commit -m change`, Want: DecisionAllow},
			{Name: "allow git commit with end-of-options operand", Command: `git commit -m message -- README.md`, Want: DecisionAllow},
			{Name: "deny git reset hard", Command: `git reset --hard HEAD`, Want: DecisionDeny, RuleID: "deny-git-reset-hard"},
			{Name: "deny git reset hard abbreviation", Command: `git reset --har HEAD`, Want: DecisionDeny, RuleID: "deny-git-reset-hard"},
			{Name: "deny rm", Command: `rm -rf build`, Want: DecisionDeny, RuleID: "deny-rm"},
			{Name: "deny absolute rm", Command: `/bin/rm file.txt`, Want: DecisionDeny, RuleID: "deny-rm"},
			{Name: "deny rmdir", Command: `rmdir old-dir`, Want: DecisionDeny, RuleID: "deny-rmdir"},
			{Name: "deny unlink", Command: `unlink old-file`, Want: DecisionDeny, RuleID: "deny-unlink"},
			{Name: "allow trash", Command: `trash old-file`, Want: DecisionAllow},
			{Name: "deny mkfs", Command: `mkfs /dev/disk9`, Want: DecisionDeny, RuleID: "deny-mkfs-family"},
			{Name: "deny mkfs variant", Command: `/sbin/mkfs.ext4 /dev/disk9`, Want: DecisionDeny, RuleID: "deny-mkfs-family"},
			{Name: "deny newfs", Command: `newfs_hfs /dev/disk9`, Want: DecisionDeny, RuleID: "deny-newfs-family"},
			{Name: "deny fdisk", Command: `fdisk /dev/disk9`, Want: DecisionDeny, RuleID: "deny-fdisk"},
			{Name: "deny dd input", Command: `dd if=/dev/disk9 of=image.bin`, Want: DecisionDeny, RuleID: "deny-dd-input"},
			{Name: "deny dd output", Command: `dd of=/dev/disk9 bs=1m`, Want: DecisionDeny, RuleID: "deny-dd-output"},
			{Name: "deny dynamic dd output", Command: `dd of="$TARGET" count=0`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny sudo", Command: `sudo git status`, Want: DecisionDeny, RuleID: "deny-sudo"},
			{Name: "deny command sudo", Command: `command sudo git status`, Want: DecisionDeny, RuleID: "deny-sudo"},
			{Name: "deny sudo empty nested shell", Command: `sudo sh -c ''`, Want: DecisionDeny, RuleID: "deny-sudo"},
			{Name: "allow empty nested shell", Command: `sh -c ''`, Want: DecisionAllow},
			{Name: "deny doas", Command: `doas git status`, Want: DecisionDeny, RuleID: "deny-doas"},
			{Name: "deny su", Command: `su root`, Want: DecisionDeny, RuleID: "deny-su"},
			{Name: "deny shutdown", Command: `shutdown -h now`, Want: DecisionDeny, RuleID: "deny-shutdown"},
			{Name: "deny reboot", Command: `reboot`, Want: DecisionDeny, RuleID: "deny-reboot"},
			{Name: "deny poweroff", Command: `poweroff`, Want: DecisionDeny, RuleID: "deny-poweroff"},
			{Name: "deny halt", Command: `halt`, Want: DecisionDeny, RuleID: "deny-halt"},
			{Name: "deny init stop", Command: `init 0`, Want: DecisionDeny, RuleID: "deny-init-stop"},
			{Name: "deny init reboot", Command: `init 6`, Want: DecisionDeny, RuleID: "deny-init-reboot"},
			{Name: "deny killall", Command: `killall node`, Want: DecisionDeny, RuleID: "deny-killall"},
			{Name: "deny pkill", Command: `pkill -f quota`, Want: DecisionDeny, RuleID: "deny-pkill"},
			{Name: "allow kill single pid", Command: `kill 12345`, Want: DecisionAllow},
			{Name: "allow kill signal single pid", Command: `kill -TERM 12345`, Want: DecisionAllow},
			{Name: "allow kill signal option single pid", Command: `kill -s TERM 12345`, Want: DecisionAllow},
			{Name: "deny kill multiple pids", Command: `kill 12345 23456`, Want: DecisionDeny, RuleID: "deny-kill-multiple-pids"},
			{Name: "deny kill multiple pids with signal", Command: `kill -TERM 12345 23456`, Want: DecisionDeny, RuleID: "deny-kill-multiple-pids-with-signal"},
			{Name: "deny kill multiple pids with signal option", Command: `kill -s TERM 12345 23456`, Want: DecisionDeny, RuleID: "deny-kill-multiple-pids-with-signal"},
			{Name: "deny kill multiple pids with zero pid", Command: `kill 12345 0`, Want: DecisionDeny, RuleID: "deny-kill-multiple-pids"},
			{Name: "deny kill multiple pids with signal zero pid", Command: `kill -TERM 12345 0`, Want: DecisionDeny, RuleID: "deny-kill-multiple-pids-with-signal"},
			{Name: "deny kill zero pid", Command: `kill 0`, Want: DecisionDeny, RuleID: "deny-kill-zero-pid"},
			{Name: "deny kill zero pid with signal", Command: `kill -TERM 0`, Want: DecisionDeny, RuleID: "deny-kill-zero-pid"},
			{Name: "deny kill zero pid with signal option", Command: `kill -s TERM 0`, Want: DecisionDeny, RuleID: "deny-kill-zero-pid"},
			{Name: "deny kill zero pid after end", Command: `kill -- 0`, Want: DecisionDeny, RuleID: "deny-kill-zero-pid"},
			{Name: "deny kill negative pid", Command: `kill -1`, Want: DecisionDeny, RuleID: "deny-kill-negative-pid"},
			{Name: "deny kill negative pid after end", Command: `kill -- -12345`, Want: DecisionDeny, RuleID: "deny-kill-negative-pid-after-end"},
			{Name: "deny kill negative pid after zero pid end", Command: `kill -- 0 -12345`, Want: DecisionDeny, RuleID: "deny-kill-negative-pid-after-end"},
			{Name: "deny kill negative pid after signal end", Command: `kill -TERM -- -12345`, Want: DecisionDeny, RuleID: "deny-kill-negative-pid-after-end"},
			{Name: "deny kill negative pid after signal option", Command: `kill -s TERM -12345 23456`, Want: DecisionDeny, RuleID: "deny-kill-negative-pid"},
			{Name: "deny dynamic kill arg", Command: `kill "$PID"`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny chmod", Command: `chmod 777 script.sh`, Want: DecisionDeny, RuleID: "deny-chmod"},
			{Name: "deny chown", Command: `chown root file`, Want: DecisionDeny, RuleID: "deny-chown"},
			{Name: "deny chgrp", Command: `chgrp admin file`, Want: DecisionDeny, RuleID: "deny-chgrp"},
			{Name: "deny gh auth token", Command: `gh auth token`, Want: DecisionDeny, RuleID: "deny-gh-auth-token"},
			{Name: "deny gh auth token with hostname", Command: `gh auth token --hostname github.com`, Want: DecisionDeny, RuleID: "deny-gh-auth-token"},
			{Name: "allow gh auth status without token", Command: `gh auth status`, Want: DecisionAllow},
			{Name: "deny gh auth status show token", Command: `gh auth status --show-token`, Want: DecisionDeny, RuleID: "deny-gh-auth-status-token-long"},
			{Name: "deny gh auth status short token", Command: `gh auth status -t`, Want: DecisionDeny, RuleID: "deny-gh-auth-status-token-short"},
			{Name: "deny gh pr merge", Command: `gh pr merge 12 --squash`, Want: DecisionDeny, RuleID: "deny-gh-pr-merge"},
			{Name: "deny gh pr merge with repo option", Command: `gh -R owner/repo pr merge 12`, Want: DecisionDeny, RuleID: "deny-gh-pr-merge"},
			{Name: "deny gh pr merge with inline repo option", Command: `gh -Rowner/repo pr merge 12`, Want: DecisionDeny, RuleID: "deny-gh-pr-merge"},
			{Name: "deny gh pr update branch", Command: `gh pr update-branch 23 --rebase`, Want: DecisionDeny, RuleID: "deny-gh-pr-update-branch"},
			{Name: "deny gh issue develop", Command: `gh issue develop 12 --name feature`, Want: DecisionDeny, RuleID: "deny-gh-issue-develop"},
			{Name: "deny gh pr revert", Command: `gh pr revert 12`, Want: DecisionDeny, RuleID: "deny-gh-pr-revert"},
			{Name: "deny gh pr close delete branch", Command: `gh pr close 23 --delete-branch`, Want: DecisionDeny, RuleID: "deny-gh-pr-close-delete-branch"},
			{Name: "deny gh pr close delete branch short", Command: `gh pr close 23 -d`, Want: DecisionDeny, RuleID: "deny-gh-pr-close-delete-branch-short"},
			{Name: "deny gh pr checkout force", Command: `gh pr checkout 23 --force`, Want: DecisionDeny, RuleID: "deny-gh-pr-checkout-force"},
			{Name: "deny gh pr checkout force short", Command: `gh pr checkout 23 -f`, Want: DecisionDeny, RuleID: "deny-gh-pr-checkout-force-short"},
			{Name: "deny gh pr co force", Command: `gh pr co 23 --force`, Want: DecisionDeny, RuleID: "deny-gh-pr-co-force"},
			{Name: "deny gh co force", Command: `gh co 23 --force`, Want: DecisionDeny, RuleID: "deny-gh-co-force"},
			{Name: "allow gh pr checkout without force", Command: `gh pr checkout 23`, Want: DecisionAllow},
			{Name: "deny gh repo visibility", Command: `gh repo edit --visibility public`, Want: DecisionDeny, RuleID: "deny-gh-repo-visibility"},
			{Name: "deny gh repo sync", Command: `gh repo sync owner/fork --source owner/upstream --force`, Want: DecisionDeny, RuleID: "deny-gh-repo-sync"},
			{Name: "deny gh repo create", Command: `gh repo create owner/new-repo --add-readme`, Want: DecisionDeny, RuleID: "deny-gh-repo-create"},
			{Name: "deny gh repo create push", Command: `gh repo create owner/new-repo --source . --push`, Want: DecisionDeny, RuleID: "deny-gh-repo-create"},
			{Name: "deny gh repo delete", Command: `gh repo delete owner/old-repo --yes`, Want: DecisionDeny, RuleID: "deny-gh-repo-delete"},
			{Name: "deny gh repo fork", Command: `gh repo fork owner/repo`, Want: DecisionDeny, RuleID: "deny-gh-repo-fork"},
			{Name: "deny gh repo deploy key add write", Command: `gh repo deploy-key add key.pub --allow-write`, Want: DecisionDeny, RuleID: "deny-gh-repo-deploy-key-add-write"},
			{Name: "deny gh repo deploy key add write short", Command: `gh repo deploy-key add key.pub -w`, Want: DecisionDeny, RuleID: "deny-gh-repo-deploy-key-add-write-short"},
			{Name: "deny gh release create", Command: `gh release create v1.2.3 --notes x`, Want: DecisionDeny, RuleID: "deny-gh-release-create"},
			{Name: "deny gh release edit", Command: `gh release edit v1.2.3 --notes x`, Want: DecisionDeny, RuleID: "deny-gh-release-edit"},
			{Name: "deny gh release upload", Command: `gh release upload v1.2.3 dist/quota.tgz`, Want: DecisionDeny, RuleID: "deny-gh-release-upload"},
			{Name: "deny gh release delete asset", Command: `gh release delete-asset v1.2.3 quota.tgz --yes`, Want: DecisionDeny, RuleID: "deny-gh-release-delete-asset"},
			{Name: "deny gh release delete", Command: `gh release delete v1.2.3 --cleanup-tag --yes`, Want: DecisionDeny, RuleID: "deny-gh-release-delete"},
			{Name: "deny gh api", Command: `gh api repos/owner/repo/pulls`, Want: DecisionDeny, RuleID: "deny-gh-api"},
			{Name: "deny gh api with hostname option", Command: `gh --hostname github.com api repos/owner/repo/pulls`, Want: DecisionDeny, RuleID: "deny-gh-api"},
			{Name: "deny gh api with repo option", Command: `gh --repo owner/repo api repos/owner/repo/pulls`, Want: DecisionDeny, RuleID: "deny-gh-api"},
			{Name: "deny gh alias set", Command: `gh alias set done 'pr merge'`, Want: DecisionDeny, RuleID: "deny-gh-alias-set"},
			{Name: "deny gh alias import", Command: `gh alias import aliases.yml`, Want: DecisionDeny, RuleID: "deny-gh-alias-import"},
			{Name: "deny gh alias delete", Command: `gh alias delete done`, Want: DecisionDeny, RuleID: "deny-gh-alias-delete"},
			{Name: "allow gh alias list", Command: `gh alias list`, Want: DecisionAllow},
			{Name: "deny gh extension exec", Command: `gh extension exec some-extension pr merge 12`, Want: DecisionDeny, RuleID: "deny-gh-extension-exec"},
			{Name: "deny gh workflow run", Command: `gh workflow run publish.yml --ref main`, Want: DecisionDeny, RuleID: "deny-gh-workflow-run"},
			{Name: "deny gh run rerun", Command: `gh run rerun 123456789`, Want: DecisionDeny, RuleID: "deny-gh-run-rerun"},
			{Name: "deny gh agent task create", Command: `gh agent-task create -F task.md`, Want: DecisionDeny, RuleID: "deny-gh-agent-task-create"},
			{Name: "deny gh codespace ssh", Command: `gh codespace ssh -c example -- ./publish.sh`, Want: DecisionDeny, RuleID: "deny-gh-codespace-ssh"},
			{Name: "deny shell alias", Command: `bash -O expand_aliases -c 'alias gp="git push"; gp origin main'`, Want: DecisionDeny, RuleID: "deny-shell-alias"},
			{Name: "deny shell source", Command: `bash -c 'source ./script.sh'`, Want: DecisionDeny, RuleID: "deny-shell-source"},
			{Name: "deny shell dot source", Command: `bash -c '. ./script.sh'`, Want: DecisionDeny, RuleID: "deny-shell-dot-source"},
			{Name: "deny shell trap", Command: `trap 'git push origin main' EXIT`, Want: DecisionDeny, RuleID: "deny-shell-trap"},
			{Name: "deny shell xargs git", Command: `printf '%s\n' 'push' 'origin' 'main' | xargs git`, Want: DecisionDeny, RuleID: "deny-shell-xargs"},
			{Name: "deny shell xargs gh", Command: `printf '%s\n' 'pr' 'merge' '12' | xargs gh`, Want: DecisionDeny, RuleID: "deny-shell-xargs"},
			{Name: "deny gh config dir dispatch", Command: `GH_CONFIG_DIR=/tmp/ghcfg gh pr view 12`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny env gh config dir dispatch", Command: `env GH_CONFIG_DIR=/tmp/ghcfg gh pr view 12`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny sudo gh config dir dispatch", Command: `sudo GH_CONFIG_DIR=/tmp/ghcfg gh pr view 12`, Want: DecisionDeny, RuleID: "deny-sudo"},
			{Name: "deny sudo preserve gh config dir dispatch", Command: `sudo --preserve-env=GH_CONFIG_DIR gh pr view 12`, Want: DecisionDeny, RuleID: "deny-sudo"},
			{Name: "deny sudo preserve all gh config dir dispatch", Command: `sudo -E gh pr view 12`, Want: DecisionDeny, RuleID: "deny-sudo"},
			{Name: "deny command sudo gh config dir dispatch", Command: `command sudo GH_CONFIG_DIR=/tmp/ghcfg gh pr view 12`, Want: DecisionDeny, RuleID: "deny-sudo"},
			{Name: "deny env sudo preserve gh config dir dispatch", Command: `env FOO=bar sudo --preserve-env=GH_CONFIG_DIR gh pr view 12`, Want: DecisionDeny, RuleID: "deny-sudo"},
			{Name: "deny exec sudo preserve all gh config dir dispatch", Command: `exec sudo -E gh pr view 12`, Want: DecisionDeny, RuleID: "deny-sudo"},
			{Name: "deny sudo preserve unrelated env", Command: `sudo --preserve-env=FOO gh pr view 12`, Want: DecisionDeny, RuleID: "deny-sudo"},
			{Name: "deny gh config dir option dispatch", Command: `gh --config-dir /tmp/ghcfg pr view 12`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny gh inline config dir option dispatch", Command: `gh --config-dir=/tmp/ghcfg pr view 12`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny unknown gh alias dispatch", Command: `gh done 12`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny unknown gh alias dispatch with home", Command: `HOME=/tmp/quota-test-home gh done 12`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "allow gh stack link ints", Command: `gh stack link 123 456`, Want: DecisionAllow},
			{Name: "deny gh stack link text", Command: `gh stack link abc 456`, Want: DecisionDeny, RuleID: "deny-gh-stack-except-link-two-ints"},
			{Name: "deny gh stack link extra", Command: `gh stack link 123 456 789`, Want: DecisionDeny, RuleID: "deny-gh-stack-except-link-two-ints"},
			{Name: "deny gh stack other", Command: `gh stack submit`, Want: DecisionDeny, RuleID: "deny-gh-stack-except-link-two-ints"},
			{Name: "allow git status", Command: `git status --short`, Want: DecisionAllow},
			{Name: "allow git maintenance", Command: `git maintenance -h`, Want: DecisionAllow},
			{Name: "allow gh pr view", Command: `gh pr view 12`, Want: DecisionAllow},
			{Name: "deny dynamic command", Command: `$cmd push origin main`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny dynamic shell script", Command: `sh -c "$cmd"`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "deny dynamic protected git", Command: `git "$subcommand" origin main`, Want: DecisionDeny, Source: string(decisionSourceUndecidable)},
			{Name: "allow dynamic value for unprotected command", Command: `echo "$HOME"`, Want: DecisionAllow},
		},
	}
	assignGitHubHistoryGuardGroups(&policy)
	return policy
}

func assignGitHubHistoryGuardGroups(policy *Policy) {
	localSafetyRules := map[string]bool{
		"deny-rm":                             true,
		"deny-rmdir":                          true,
		"deny-unlink":                         true,
		"deny-mkfs-family":                    true,
		"deny-newfs-family":                   true,
		"deny-fdisk":                          true,
		"deny-dd-input":                       true,
		"deny-dd-output":                      true,
		"deny-sudo":                           true,
		"deny-doas":                           true,
		"deny-su":                             true,
		"deny-shutdown":                       true,
		"deny-reboot":                         true,
		"deny-poweroff":                       true,
		"deny-halt":                           true,
		"deny-init-stop":                      true,
		"deny-init-reboot":                    true,
		"deny-killall":                        true,
		"deny-pkill":                          true,
		"deny-kill-multiple-pids":             true,
		"deny-kill-multiple-pids-with-signal": true,
		"deny-kill-zero-pid":                  true,
		"deny-kill-negative-pid":              true,
		"deny-kill-negative-pid-after-end":    true,
		"deny-chmod":                          true,
		"deny-chown":                          true,
		"deny-chgrp":                          true,
		"deny-gh-auth-token":                  true,
		"deny-gh-auth-status-token-long":      true,
		"deny-gh-auth-status-token-short":     true,
	}
	for i := range policy.Rules {
		if localSafetyRules[policy.Rules[i].ID] {
			policy.Rules[i].Group = PolicyGroupLocalSystemSecretSafety
		} else {
			policy.Rules[i].Group = PolicyGroupRemoteCodeRefMutation
		}
	}
	metadataTests := map[string]bool{
		"allow pr create with explicit head":   true,
		"allow issue create":                   true,
		"allow pr edit":                        true,
		"allow pr comment":                     true,
		"allow issue comment":                  true,
		"allow issue edit":                     true,
		"allow issue view":                     true,
		"allow pr close without branch delete": true,
		"allow gh pr view":                     true,
		"allow gh stack link ints":             true,
	}
	localSafetyTests := map[string]bool{
		"deny rm":                      true,
		"deny absolute rm":             true,
		"deny rmdir":                   true,
		"deny unlink":                  true,
		"allow trash":                  true,
		"deny mkfs":                    true,
		"deny mkfs variant":            true,
		"deny newfs":                   true,
		"deny fdisk":                   true,
		"deny dd input":                true,
		"deny dd output":               true,
		"deny dynamic dd output":       true,
		"deny sudo":                    true,
		"deny command sudo":            true,
		"deny sudo empty nested shell": true,
		"allow empty nested shell":     true,
		"deny sudo env assignment wrapped git push":          true,
		"deny sudo chdir wrapped git push":                   true,
		"deny sudo inline user wrapped git push":             true,
		"deny sudo bash startup hidden script":               true,
		"deny sudo login shell hidden startup":               true,
		"deny sudo gh config dir dispatch":                   true,
		"deny sudo preserve gh config dir dispatch":          true,
		"deny sudo preserve all gh config dir dispatch":      true,
		"deny command sudo gh config dir dispatch":           true,
		"deny env sudo preserve gh config dir dispatch":      true,
		"deny exec sudo preserve all gh config dir dispatch": true,
		"deny sudo preserve unrelated env":                   true,
		"deny doas":                                          true,
		"deny su":                                            true,
		"deny shutdown":                                      true,
		"deny reboot":                                        true,
		"deny poweroff":                                      true,
		"deny halt":                                          true,
		"deny init stop":                                     true,
		"deny init reboot":                                   true,
		"deny killall":                                       true,
		"deny pkill":                                         true,
		"allow kill single pid":                              true,
		"allow kill signal single pid":                       true,
		"allow kill signal option single pid":                true,
		"deny kill multiple pids":                            true,
		"deny kill multiple pids with signal":                true,
		"deny kill multiple pids with signal option":         true,
		"deny kill multiple pids with zero pid":              true,
		"deny kill multiple pids with signal zero pid":       true,
		"deny kill zero pid":                                 true,
		"deny kill zero pid with signal":                     true,
		"deny kill zero pid with signal option":              true,
		"deny kill zero pid after end":                       true,
		"deny kill negative pid":                             true,
		"deny kill negative pid after end":                   true,
		"deny kill negative pid after zero pid end":          true,
		"deny kill negative pid after signal end":            true,
		"deny kill negative pid after signal option":         true,
		"deny dynamic kill arg":                              true,
		"deny chmod":                                         true,
		"deny chown":                                         true,
		"deny chgrp":                                         true,
		"deny gh auth token":                                 true,
		"deny gh auth token with hostname":                   true,
		"allow gh auth status without token":                 true,
		"deny gh auth status show token":                     true,
		"deny gh auth status short token":                    true,
	}
	for i := range policy.Tests {
		switch {
		case metadataTests[policy.Tests[i].Name]:
			policy.Tests[i].Group = PolicyGroupGitHubCollaborationMetadata
		case localSafetyTests[policy.Tests[i].Name]:
			policy.Tests[i].Group = PolicyGroupLocalSystemSecretSafety
		case policy.Tests[i].Want == DecisionDeny:
			policy.Tests[i].Group = PolicyGroupRemoteCodeRefMutation
		}
	}
}

func exactArgs(args ...string) []ArgPattern {
	patterns := make([]ArgPattern, 0, len(args))
	for _, arg := range args {
		patterns = append(patterns, ArgPattern{Exact: arg})
	}
	return patterns
}
